import { Check, LoaderCircle } from 'lucide-react';
import { type SyntheticEvent, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import type { HealthFocus } from '@/lib/contracts';
import { getCopy, type Locale } from '@/lib/copy';
import { dashboardTargets, type DashboardTargetKey } from '@/lib/dashboard-model';

export function HealthTargetsPanel({ targets, saving, onSave, healthFocuses, savingFocuses, onSaveFocuses, locale }: { targets: Record<DashboardTargetKey, number>; saving: boolean; onSave: (values: Record<DashboardTargetKey, number>) => void; healthFocuses: HealthFocus[]; savingFocuses: boolean; onSaveFocuses: (focuses: HealthFocus[]) => void; locale: Locale }) {
  const c = getCopy(locale);
  const [drafts, setDrafts] = useState<Record<DashboardTargetKey, string>>(() => Object.fromEntries(dashboardTargets.map((target) => [target.key, String(targets[target.key])])) as Record<DashboardTargetKey, string>);
  const [focuses, setFocuses] = useState<HealthFocus[]>(healthFocuses);
  const labels: Record<DashboardTargetKey, string> = { calories: c.settings.calories, protein: c.settings.protein, fiber: c.settings.fiber, sodium: c.settings.sodium };
  const options: Array<{ key: HealthFocus; label: string; description: string }> = [{ key: 'blood_pressure', label: c.settings.bloodPressure, description: c.settings.bloodPressureDescription }, { key: 'cholesterol', label: c.settings.cholesterol, description: c.settings.cholesterolDescription }, { key: 'blood_glucose', label: c.settings.bloodGlucose, description: c.settings.bloodGlucoseDescription }, { key: 'uric_acid', label: c.settings.uricAcid, description: c.settings.uricAcidDescription }];
  function submit(event: SyntheticEvent<HTMLFormElement>) { event.preventDefault(); const next = Object.fromEntries(dashboardTargets.map((target) => [target.key, Number(drafts[target.key])])) as Record<DashboardTargetKey, number>; if (Object.values(next).some((value) => !Number.isFinite(value) || value < 0)) return; onSave(next); }
  function toggleFocus(focus: HealthFocus) { setFocuses((current) => current.includes(focus) ? current.filter((item) => item !== focus) : [...current, focus]); }
  return <><Card className="mt-7 border-none shadow-sm"><CardHeader><CardTitle>{c.settings.title}</CardTitle><CardDescription>{c.settings.targetsDescription}</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-4">{dashboardTargets.map((target) => <label key={target.key} className="flex items-center gap-4 rounded-xl bg-slate-50 p-4"><span className={`size-2.5 rounded-full ${target.color}`} /><span className="min-w-24 flex-1 font-semibold">{labels[target.key]}</span><Input type="number" min="0" step={target.key === 'calories' || target.key === 'sodium' ? '1' : '0.1'} inputMode="decimal" value={drafts[target.key]} onChange={(event) => setDrafts((current) => ({ ...current, [target.key]: event.target.value }))} aria-label={`${labels[target.key]} ${c.settings.targetSuffix}`} className="w-28 bg-white" required /><span className="w-10 text-sm text-slate-500">{target.unit}</span></label>)}<Button type="submit" disabled={saving} className="w-full bg-emerald-800 hover:bg-emerald-900">{saving ? <><LoaderCircle className="animate-spin" /> {c.common.saving}</> : <><Check /> {c.settings.saveTargets}</>}</Button></form></CardContent></Card><Card className="mt-6 border-none shadow-sm"><CardHeader><CardTitle>{c.settings.healthFocuses}</CardTitle><CardDescription>{c.settings.healthFocusDescription}</CardDescription></CardHeader><CardContent><div className="space-y-3">{options.map((option) => { const selected = focuses.includes(option.key); return <button type="button" key={option.key} aria-label={`${selected ? c.settings.removeFocus : c.settings.addFocus} ${option.label} ${c.settings.focusSuffix}`} aria-pressed={selected} onClick={() => toggleFocus(option.key)} className={`w-full rounded-xl border p-4 text-left transition-colors ${selected ? 'border-emerald-600 bg-emerald-50' : 'border-slate-200 bg-white hover:bg-slate-50'}`}><span className="flex items-center justify-between gap-4"><span><span className="block font-semibold">{option.label}</span><span className="mt-1 block text-sm leading-5 text-slate-600">{option.description}</span></span><span className={`grid size-6 place-items-center rounded-full border ${selected ? 'border-emerald-700 bg-emerald-700 text-white' : 'border-slate-300 text-transparent'}`}>✓</span></span></button>; })}</div><Button type="button" onClick={() => onSaveFocuses(focuses)} disabled={savingFocuses} className="mt-5 w-full bg-emerald-800 hover:bg-emerald-900">{savingFocuses ? <><LoaderCircle className="animate-spin" /> {c.common.saving}</> : <><Check /> {c.settings.saveHealthFocuses}</>}</Button></CardContent></Card></>;
}
