/** Shared, presentation-only English/Vietnamese product copy. */
export const supportedLocales = ['en', 'vi'] as const;
export type Locale = (typeof supportedLocales)[number];

export const localeMetadata: Record<
  Locale,
  { label: string; documentLang: string }
> = {
  en: { label: 'English', documentLang: 'en' },
  vi: { label: 'Tiếng Việt', documentLang: 'vi' },
};

const englishCopy = {
  app: {
    name: 'Nourishwell',
    tagline: 'Private nutrition and movement support',
    language: 'Language',
    changeLanguage: 'Change language',
  },
  nav: {
    today: 'Today',
    capture: 'Capture',
    measurements: 'Measurements',
    workouts: 'Workouts',
    settings: 'Settings',
    openNavigation: 'Open navigation',
    closeNavigation: 'Close navigation',
  },
  common: {
    back: 'Back',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    save: 'Save',
    saving: 'Saving…',
    edit: 'Edit',
    delete: 'Delete',
    retry: 'Try again',
    loading: 'Loading…',
    required: 'Required',
    optional: 'Optional',
    private: 'Private',
  },
  today: {
    confirmedOnly: 'Confirmed meal records only',
    title: 'Today, with clear evidence.',
    logMeal: 'Log a meal',
    calories: 'Calories',
    protein: 'Protein',
    fiber: 'Fiber',
    sodium: 'Sodium',
    remaining: 'remaining',
    noTarget: 'No daily target set',
    mealLog: 'Today’s meal log',
    confirmedEntries: 'Your confirmed entries',
    loadingRecords: 'Loading your private records…',
    evidenceTitle: 'Evidence stays visible.',
    evidenceDescription:
      'Each saved meal keeps its ingredients, serving assumption, estimate source, and confidence. Nothing is auto-saved.',
    guidanceTitle: 'Health guidance comes next',
    guidanceDescription:
      'Personal targets and clinician-approved rules will be connected after onboarding. Today’s starter targets are not medical advice.',
    emptyTitle: 'No meals confirmed today',
    emptyDescription:
      'Start with a short typed description. You can edit every estimate before saving.',
    captureMeal: 'Capture a meal',
  },
  mealCapture: {
    eyebrow: 'Capture · review required',
    title: 'What did you have?',
    description:
      'Describe a meal, scan a barcode, or search a food composition database.',
    text: 'Text',
    barcode: 'Barcode',
    vietnamData: 'Vietnam data',
    usda: 'USDA',
    mealPlaceholder: 'For example: phở bò with extra herbs, no chili oil',
    barcodePlaceholder: 'Enter an 8–14 digit barcode',
    vietnamDishPlaceholder: 'For example: cơm gà',
    vietnamIngredientPlaceholder: 'For example: thịt gà',
    usdaPlaceholder: 'For example: chicken breast, broccoli',
    analyse: 'Analyse and review',
    analysing: 'Preparing review…',
    reviewTitle: 'Review before saving',
    emptyReviewTitle: 'Nothing is saved automatically',
    emptyReviewDescription:
      'Analyse a meal, inspect the ingredients and values, then confirm it yourself.',
    confidence: 'confidence',
    confirmMeal: 'Confirm meal',
    discardReview: 'Discard review',
    servingAssumption: 'Serving assumption',
    ingredients: 'Ingredients',
    source: 'Source',
    estimate: 'Estimate',
    manualEntry: 'Manual entry',
    reviewRequired: 'Review required before saving.',
    vietnamDish: 'Dish / Món ăn',
    vietnamIngredient: 'Ingredient / Thực phẩm',
    vietnamSearchLabel: 'Vietnam nutrition catalog search',
    usdaSearchLabel: 'USDA food search',
    typedProviderNote:
      'Typed meals use transparent starter rules. Always review the values.',
    barcodeProviderNote:
      'Barcode lookup uses Open Food Facts product data. The product label and your confirmation take priority.',
    vietnamProviderNote:
      'Vietnam nutrition catalog values are database-derived. Review the match and your serving before saving.',
    usdaProviderNote:
      'USDA FoodData Central uses a 100 g database basis and requires a private API key. Review the food and serving before saving.',
    reviewPlaceholder: 'Your meal will appear here',
    detectedIngredients: 'Detected ingredients',
    serving: 'Serving',
    sourceAndReview: 'Source and review note',
    conditionChecks: 'Condition-specific checks',
    conditionChecksDescription:
      'Versioned tracking rules—not diagnoses or medical advice. They do not alter the nutrient values above.',
    discard: 'Discard',
    confirmAndSave: 'Confirm & save',
  },
  measurements: {
    eyebrow: 'Measurements',
    title: 'Track a measurement',
    description:
      'Enter a value you measured yourself. Review it before saving.',
    add: 'Add measurement',
    metric: 'Measurement type',
    customLabel: 'Lab test name',
    customLabelPlaceholder: 'For example: Vitamin D',
    value: 'Value',
    secondaryValue: 'Second value',
    unit: 'Unit',
    unitPlaceholder: 'For example: ng/mL',
    measuredAt: 'Measured at',
    saveMeasurement: 'Save measurement',
    emptyTitle: 'No measurements yet',
    emptyDescription: 'Your confirmed measurements will appear here.',
    metrics: {
      weight: 'Weight',
      bloodPressure: 'Blood pressure',
      bloodGlucose: 'Blood glucose',
      totalCholesterol: 'Total cholesterol',
      uricAcid: 'Uric acid',
      customLab: 'Custom lab result',
    },
  },
  workouts: {
    eyebrow: 'Movement safety',
    title: 'Workout readiness',
    description:
      'Complete this screen before the app can generate a workout plan. It does not replace medical advice.',
    screeningTitle: 'Tell us what applies today',
    screeningDescription:
      'Select every statement that applies. Any selection pauses new plan generation for professional review.',
    chestPain: 'Chest pain, pressure, or tightness with activity',
    faintingOrDizziness: 'Fainting, new severe dizziness, or confusion',
    severeShortnessOfBreath: 'Unusual or severe shortness of breath',
    irregularHeartbeat: 'A fast or irregular heartbeat with activity',
    clinicianRestriction: 'A clinician has told me to avoid or restrict exercise',
    exerciseGlucoseRisk:
      'I use insulin or a medicine that can lower glucose and do not have an exercise plan from my care team',
    confirm: 'Confirm workout readiness',
    clearedTitle: 'Readiness confirmed',
    clearedDescription:
      'No gate flags were reported. A future plan will still use your equipment, recovery, and clinician restrictions.',
    pausedTitle: 'Workout plan paused',
    pausedDescription:
      'Do not start a new program from this app until the reported concern is reviewed by an appropriate clinician. Seek urgent care for severe or emergency symptoms.',
    incompleteTitle: 'Readiness required',
    incompleteDescription:
      'A workout plan cannot be generated until you complete this safety screen.',
    catalogTitle: 'Starter exercise library',
    catalogDescription:
      'These movements are a transparent starter catalog, not a workout prescription. A future plan will choose only compatible options.',
    technique: 'Technique',
    regression: 'Make it easier',
    progression: 'Progress later',
    equipment: 'Equipment',
    planTitle: 'Your starter week',
    previewPlan: 'Generate plan preview',
    confirmPlan: 'Confirm this plan',
    planPreviewNote:
      'Review this conservative plan before saving. It is intentionally not adapted to symptoms, recovery, or equipment changes yet.',
    confirmedPlanNote:
      'Confirmed plan. Log completion and recovery in the upcoming workout-log flow.',
    minutes: 'minutes',
    effort: 'Effort',
    logTitle: 'Log a completed session',
    session: 'Session',
    duration: 'Actual duration',
    enjoyment: 'Enjoyment',
    pain: 'I had pain during this session',
    concerningSymptoms: 'I had concerning symptoms during this session',
    preGlucose: 'Before-exercise glucose (optional, mmol/L)',
    postGlucose: 'After-exercise glucose (optional, mmol/L)',
    saveLog: 'Save workout log',
    safetyLogNote:
      'Pain or concerning symptoms save this session as stopped for safety and pause future progression.',
    logHistory: 'Recent workout logs',
    sets: 'Sets',
    reps: 'Reps per set',
    load: 'Load (optional)',
    heartRate: 'Average heart rate (optional)',
    checkin: 'Run recovery check-in',
    checkinTitle: 'Weekly check-in',
    checkinMaintain: 'Maintain the current plan; no automatic progression is applied.',
    checkinRepeat: 'Repeat the current plan before changing it; adherence is still building.',
    checkinHold: 'Hold progression and review the reported safety concern with an appropriate clinician.',
  },
  settings: {
    eyebrow: 'Settings',
    title: 'Personal targets',
    description:
      'Use targets you set for yourself. Clinician-defined targets always take priority.',
    calories: 'Calories',
    protein: 'Protein',
    fiber: 'Fiber',
    sodium: 'Sodium',
    saveTargets: 'Save personal targets',
    healthFocuses: 'Health focuses',
    healthFocusDescription: 'Optional tracking preferences, not diagnoses.',
    saveHealthFocuses: 'Save health focuses',
    dataPrivacy: 'Privacy and data',
    exportData: 'Export my data',
    deleteData: 'Delete my data',
    targetsDescription:
      'These targets guide the Today dashboard only; they are not medical advice.',
    targetSuffix: 'target',
    bloodPressure: 'Blood pressure',
    bloodPressureDescription: 'Prioritize sodium-related review checks.',
    cholesterol: 'Cholesterol',
    cholesterolDescription: 'Prioritize fiber-pattern review checks.',
    bloodGlucose: 'Blood glucose',
    bloodGlucoseDescription:
      'Saved now; exercise and carbohydrate safety rules come later.',
    uricAcid: 'Uric acid / gout',
    uricAcidDescription: 'Saved now; purine-risk rules come later.',
    addFocus: 'Add',
    removeFocus: 'Remove',
    focusSuffix: 'health focus',
    sensitiveDataNotice:
      'Do not enter medication, symptoms, or clinician notes here yet. Those need the upcoming encrypted health-profile flow.',
  },
  onboarding: {
    eyebrow: 'Profile setup',
    title: 'Plan around your real life',
    description:
      'Save what is useful for meal and home-workout planning. You can save a partial setup and return later.',
    complete: 'Planning basics complete',
    inProgress: 'Planning basics in progress',
    goal: 'Primary goal',
    height: 'Height (cm)',
    weight: 'Current weight (kg)',
    age: 'Age',
    sex: 'Sex for metabolic calculations',
    activity: 'Usual activity',
    training: 'Training history',
    sleep: 'Typical sleep (hours)',
    days: 'Available training days',
    equipment: 'Equipment available now',
    environments: 'Training environments',
    restrictions: 'Clinician exercise restrictions',
    preferences: 'Food preferences',
    allergies: 'Food allergies',
    contexts: 'Health tracking contexts',
    injuries: 'Current movement concerns',
    symptoms: 'Current exercise symptoms',
    preferenceOmnivore: 'Omnivore', preferenceVegetarian: 'Vegetarian', preferenceVegan: 'Vegan', preferencePescatarian: 'Pescatarian', preferenceHalal: 'Halal', preferenceLowSodium: 'Lower sodium', preferenceLowPurine: 'Lower purine',
    allergyMilk: 'Milk', allergyEgg: 'Egg', allergyFish: 'Fish', allergyShellfish: 'Shellfish', allergyPeanut: 'Peanut', allergyTreeNut: 'Tree nuts', allergySoy: 'Soy', allergyWheat: 'Wheat', allergySesame: 'Sesame',
    contextBloodPressure: 'Blood pressure', contextCholesterol: 'Cholesterol', contextBloodGlucose: 'Blood glucose', contextUricAcid: 'Uric acid',
    injuryBack: 'Back pain', injuryJoint: 'Joint pain', injuryBalance: 'Balance concern',
    symptomNone: 'No symptoms', symptomChest: 'Chest discomfort', symptomDizziness: 'Dizziness', symptomBreath: 'Shortness of breath',
    save: 'Save profile setup',
    goalWeightLoss: 'Weight loss',
    goalMaintain: 'Maintain weight',
    goalMuscleGain: 'Muscle gain',
    goalFitness: 'Fitness',
    goalHealthTracking: 'Health tracking',
    sexFemale: 'Female',
    sexMale: 'Male',
    sexNotSpecified: 'Prefer not to specify',
    activitySedentary: 'Mostly sitting',
    activityLight: 'Lightly active',
    activityModerate: 'Moderately active',
    activityActive: 'Active',
    activityVeryActive: 'Very active',
    trainingNew: 'New to exercise',
    trainingBeginner: 'Beginner',
    trainingRegular: 'Regular training',
    dayMon: 'Mon', dayTue: 'Tue', dayWed: 'Wed', dayThu: 'Thu', dayFri: 'Fri', daySat: 'Sat', daySun: 'Sun',
    equipmentBodyweight: 'Bodyweight', equipmentChair: 'Chair', equipmentMat: 'Exercise mat', equipmentBicycle: 'Bicycle', equipmentTreadmill: 'Mini treadmill', equipmentBand: 'Resistance band', equipmentDumbbells: 'Dumbbells', equipmentGym: 'Gym',
    environmentHome: 'Home', environmentOutdoors: 'Outdoors', environmentGym: 'Gym',
    restrictionIntensity: 'Avoid high intensity', restrictionResistance: 'Avoid resistance training', restrictionImpact: 'Avoid impact exercise', restrictionGlucose: 'Monitor glucose',
  },
  sensitiveNotes: {
    eyebrow: 'Encrypted health notes',
    title: 'Private notes for your plan',
    description: 'These notes are encrypted before storage. They are not shown in reminders or used to diagnose or change medication.',
    medication: 'Medication or exercise-safety notes',
    clinician: 'Clinician instructions',
    symptoms: 'Additional symptom notes',
    save: 'Save encrypted notes',
    unavailable: 'Encrypted health notes are unavailable until the server-side encryption key is configured.',
  },
  safety: {
    notMedicalAdvice:
      'This information is for general wellness support and is not medical advice.',
    reviewBeforeSaving:
      'Review values, serving assumptions, and sources before saving.',
    noAutomaticSaving: 'Nothing is saved automatically.',
    seekUrgentCare:
      'Seek urgent medical care for severe symptoms or an emergency.',
    stopTraining:
      'Stop activity if you have chest pain, severe shortness of breath, fainting, sudden dizziness, or concerning new symptoms.',
    clinicianPriority:
      'Follow your clinician’s advice. Clinician-defined targets and restrictions take priority.',
    noDiagnosis:
      'Tracking preferences and meal findings are not diagnoses or treatment recommendations.',
    sensitiveData:
      'Do not enter medication details, symptoms, or clinician notes until the encrypted health-profile flow is available.',
  },
} as const;

type StringLeafShape<T> = T extends string
  ? string
  : { [Key in keyof T]: StringLeafShape<T[Key]> };

/** The stable key structure every supported locale must provide. */
export type ProductCopy = StringLeafShape<typeof englishCopy>;

const vietnameseCopy: ProductCopy = {
  app: {
    name: 'Nourishwell',
    tagline: 'Hỗ trợ riêng tư về dinh dưỡng và vận động',
    language: 'Ngôn ngữ',
    changeLanguage: 'Đổi ngôn ngữ',
  },
  nav: {
    today: 'Hôm nay',
    capture: 'Ghi bữa ăn',
    measurements: 'Chỉ số',
    workouts: 'Tập luyện',
    settings: 'Cài đặt',
    openNavigation: 'Mở điều hướng',
    closeNavigation: 'Đóng điều hướng',
  },
  common: {
    back: 'Quay lại',
    cancel: 'Hủy',
    close: 'Đóng',
    confirm: 'Xác nhận',
    save: 'Lưu',
    saving: 'Đang lưu…',
    edit: 'Chỉnh sửa',
    delete: 'Xóa',
    retry: 'Thử lại',
    loading: 'Đang tải…',
    required: 'Bắt buộc',
    optional: 'Tùy chọn',
    private: 'Riêng tư',
  },
  today: {
    confirmedOnly: 'Chỉ các bữa ăn đã xác nhận',
    title: 'Hôm nay, với thông tin rõ ràng.',
    logMeal: 'Ghi bữa ăn',
    calories: 'Năng lượng',
    protein: 'Chất đạm',
    fiber: 'Chất xơ',
    sodium: 'Natri',
    remaining: 'còn lại',
    noTarget: 'Chưa đặt mục tiêu hằng ngày',
    mealLog: 'Nhật ký bữa ăn hôm nay',
    confirmedEntries: 'Các mục đã xác nhận',
    loadingRecords: 'Đang tải dữ liệu riêng tư của bạn…',
    evidenceTitle: 'Thông tin nguồn luôn hiển thị.',
    evidenceDescription:
      'Mỗi bữa ăn đã lưu giữ lại nguyên liệu, khẩu phần giả định, nguồn ước tính và độ tin cậy. Không có gì được tự động lưu.',
    guidanceTitle: 'Hướng dẫn sức khỏe sẽ có tiếp theo',
    guidanceDescription:
      'Mục tiêu cá nhân và các quy tắc được bác sĩ chấp thuận sẽ được kết nối sau phần thiết lập ban đầu. Các mục tiêu mẫu hôm nay không phải lời khuyên y tế.',
    emptyTitle: 'Hôm nay chưa có bữa ăn nào được xác nhận',
    emptyDescription:
      'Bắt đầu bằng một mô tả ngắn. Bạn có thể chỉnh sửa mọi ước tính trước khi lưu.',
    captureMeal: 'Ghi bữa ăn',
  },
  mealCapture: {
    eyebrow: 'Ghi nhận · cần xem lại',
    title: 'Bạn đã ăn gì?',
    description:
      'Mô tả bữa ăn, quét mã vạch hoặc tìm trong cơ sở dữ liệu thành phần thực phẩm.',
    text: 'Nhập món ăn',
    barcode: 'Mã vạch',
    vietnamData: 'Dữ liệu Việt Nam',
    usda: 'USDA',
    mealPlaceholder: 'Ví dụ: phở bò thêm rau thơm, không dầu ớt',
    barcodePlaceholder: 'Nhập mã vạch gồm 8–14 chữ số',
    vietnamDishPlaceholder: 'Ví dụ: cơm gà',
    vietnamIngredientPlaceholder: 'Ví dụ: thịt gà',
    usdaPlaceholder: 'Ví dụ: ức gà, bông cải xanh',
    analyse: 'Phân tích và xem lại',
    analysing: 'Đang chuẩn bị bản xem lại…',
    reviewTitle: 'Xem lại trước khi lưu',
    emptyReviewTitle: 'Không có gì được tự động lưu',
    emptyReviewDescription:
      'Phân tích bữa ăn, kiểm tra nguyên liệu và các giá trị, rồi tự bạn xác nhận.',
    confidence: 'độ tin cậy',
    confirmMeal: 'Xác nhận bữa ăn',
    discardReview: 'Bỏ bản xem lại',
    servingAssumption: 'Khẩu phần giả định',
    ingredients: 'Nguyên liệu',
    source: 'Nguồn',
    estimate: 'Ước tính',
    manualEntry: 'Nhập thủ công',
    reviewRequired: 'Cần xem lại trước khi lưu.',
    vietnamDish: 'Món ăn / Dish',
    vietnamIngredient: 'Thực phẩm / Ingredient',
    vietnamSearchLabel: 'Tìm kiếm trong cơ sở dữ liệu dinh dưỡng Việt Nam',
    usdaSearchLabel: 'Tìm kiếm thực phẩm USDA',
    typedProviderNote:
      'Các bữa ăn nhập chữ dùng quy tắc khởi đầu minh bạch. Luôn kiểm tra lại các giá trị.',
    barcodeProviderNote:
      'Tra mã vạch dùng dữ liệu sản phẩm Open Food Facts. Nhãn sản phẩm và xác nhận của bạn được ưu tiên.',
    vietnamProviderNote:
      'Giá trị từ cơ sở dữ liệu dinh dưỡng Việt Nam. Hãy kiểm tra món khớp và khẩu phần trước khi lưu.',
    usdaProviderNote:
      'USDA FoodData Central dùng cơ sở dữ liệu theo 100 g và cần khóa API riêng tư. Hãy kiểm tra thực phẩm và khẩu phần trước khi lưu.',
    reviewPlaceholder: 'Bữa ăn của bạn sẽ xuất hiện ở đây',
    detectedIngredients: 'Nguyên liệu được nhận diện',
    serving: 'Khẩu phần',
    sourceAndReview: 'Nguồn và ghi chú xem lại',
    conditionChecks: 'Kiểm tra theo tình trạng',
    conditionChecksDescription:
      'Các quy tắc theo dõi có phiên bản — không phải chẩn đoán hay lời khuyên y tế. Chúng không thay đổi giá trị dinh dưỡng ở trên.',
    discard: 'Bỏ',
    confirmAndSave: 'Xác nhận và lưu',
  },
  measurements: {
    eyebrow: 'Chỉ số',
    title: 'Theo dõi chỉ số',
    description: 'Nhập giá trị bạn tự đo. Hãy xem lại trước khi lưu.',
    add: 'Thêm chỉ số',
    metric: 'Loại chỉ số',
    customLabel: 'Tên xét nghiệm',
    customLabelPlaceholder: 'Ví dụ: Vitamin D',
    value: 'Giá trị',
    secondaryValue: 'Giá trị thứ hai',
    unit: 'Đơn vị',
    unitPlaceholder: 'Ví dụ: ng/mL',
    measuredAt: 'Thời điểm đo',
    saveMeasurement: 'Lưu chỉ số',
    emptyTitle: 'Chưa có chỉ số nào',
    emptyDescription: 'Các chỉ số bạn xác nhận sẽ xuất hiện ở đây.',
    metrics: {
      weight: 'Cân nặng',
      bloodPressure: 'Huyết áp',
      bloodGlucose: 'Đường huyết',
      totalCholesterol: 'Cholesterol toàn phần',
      uricAcid: 'Axit uric',
      customLab: 'Kết quả xét nghiệm khác',
    },
  },
  workouts: {
    eyebrow: 'An toàn vận động',
    title: 'Sẵn sàng tập luyện',
    description:
      'Hoàn thành phần này trước khi ứng dụng có thể tạo kế hoạch tập. Phần này không thay thế lời khuyên y tế.',
    screeningTitle: 'Cho biết điều nào đúng với bạn hôm nay',
    screeningDescription:
      'Chọn tất cả điều phù hợp. Bất kỳ lựa chọn nào cũng sẽ tạm dừng tạo kế hoạch mới để cần đánh giá chuyên môn.',
    chestPain: 'Đau, tức hoặc nặng ngực khi vận động',
    faintingOrDizziness: 'Ngất, chóng mặt nặng mới xuất hiện hoặc lú lẫn',
    severeShortnessOfBreath: 'Khó thở bất thường hoặc nghiêm trọng',
    irregularHeartbeat: 'Tim đập nhanh hoặc không đều khi vận động',
    clinicianRestriction: 'Bác sĩ đã yêu cầu tôi tránh hoặc hạn chế tập luyện',
    exerciseGlucoseRisk:
      'Tôi dùng insulin hoặc thuốc có thể làm hạ đường huyết và chưa có kế hoạch tập từ đội ngũ chăm sóc',
    confirm: 'Xác nhận sẵn sàng tập luyện',
    clearedTitle: 'Đã xác nhận sẵn sàng',
    clearedDescription:
      'Bạn không báo cáo cờ an toàn nào. Kế hoạch trong tương lai vẫn sẽ dùng thiết bị, hồi phục và hạn chế của bác sĩ.',
    pausedTitle: 'Đã tạm dừng kế hoạch tập',
    pausedDescription:
      'Không bắt đầu chương trình mới từ ứng dụng này cho đến khi vấn đề được báo cáo được chuyên gia phù hợp xem xét. Hãy tìm trợ giúp khẩn cấp khi có triệu chứng nặng hoặc cấp cứu.',
    incompleteTitle: 'Cần hoàn thành sàng lọc',
    incompleteDescription:
      'Không thể tạo kế hoạch tập cho đến khi bạn hoàn thành màn hình an toàn này.',
    catalogTitle: 'Thư viện bài tập khởi đầu',
    catalogDescription:
      'Các động tác này là danh mục khởi đầu minh bạch, không phải đơn tập. Kế hoạch trong tương lai chỉ chọn các lựa chọn phù hợp.',
    technique: 'Kỹ thuật',
    regression: 'Giảm độ khó',
    progression: 'Tiến triển sau',
    equipment: 'Dụng cụ',
    planTitle: 'Tuần khởi đầu của bạn',
    previewPlan: 'Tạo bản xem trước kế hoạch',
    confirmPlan: 'Xác nhận kế hoạch này',
    planPreviewNote:
      'Hãy xem lại kế hoạch thận trọng này trước khi lưu. Hiện kế hoạch chưa điều chỉnh theo triệu chứng, hồi phục hoặc thay đổi thiết bị.',
    confirmedPlanNote:
      'Kế hoạch đã xác nhận. Hãy ghi nhận hoàn thành và hồi phục trong luồng nhật ký tập sắp tới.',
    minutes: 'phút',
    effort: 'Cường độ',
    logTitle: 'Ghi nhận buổi tập đã hoàn thành',
    session: 'Buổi tập',
    duration: 'Thời lượng thực tế',
    enjoyment: 'Mức yêu thích',
    pain: 'Tôi bị đau trong buổi tập này',
    concerningSymptoms: 'Tôi có triệu chứng đáng lo trong buổi tập này',
    preGlucose: 'Đường huyết trước tập (tùy chọn, mmol/L)',
    postGlucose: 'Đường huyết sau tập (tùy chọn, mmol/L)',
    saveLog: 'Lưu nhật ký tập',
    safetyLogNote:
      'Đau hoặc triệu chứng đáng lo sẽ lưu buổi tập là dừng vì an toàn và tạm dừng tăng tiến trong tương lai.',
    logHistory: 'Nhật ký tập gần đây',
    sets: 'Số hiệp',
    reps: 'Số lần mỗi hiệp',
    load: 'Tải trọng (tùy chọn)',
    heartRate: 'Nhịp tim trung bình (tùy chọn)',
    checkin: 'Thực hiện đánh giá hồi phục',
    checkinTitle: 'Đánh giá hằng tuần',
    checkinMaintain: 'Duy trì kế hoạch hiện tại; không tự động tăng tiến.',
    checkinRepeat: 'Lặp lại kế hoạch hiện tại trước khi thay đổi; mức tuân thủ vẫn đang xây dựng.',
    checkinHold: 'Tạm dừng tăng tiến và trao đổi vấn đề an toàn đã báo cáo với chuyên gia phù hợp.',
  },
  settings: {
    eyebrow: 'Cài đặt',
    title: 'Mục tiêu cá nhân',
    description:
      'Dùng các mục tiêu do bạn tự đặt. Mục tiêu do bác sĩ chỉ định luôn được ưu tiên.',
    calories: 'Năng lượng',
    protein: 'Chất đạm',
    fiber: 'Chất xơ',
    sodium: 'Natri',
    saveTargets: 'Lưu mục tiêu cá nhân',
    healthFocuses: 'Mối quan tâm sức khỏe',
    healthFocusDescription: 'Tùy chọn theo dõi, không phải chẩn đoán.',
    saveHealthFocuses: 'Lưu mối quan tâm sức khỏe',
    dataPrivacy: 'Quyền riêng tư và dữ liệu',
    exportData: 'Xuất dữ liệu của tôi',
    deleteData: 'Xóa dữ liệu của tôi',
    targetsDescription:
      'Các mục tiêu này chỉ dùng cho bảng Hôm nay; chúng không phải lời khuyên y tế.',
    targetSuffix: 'mục tiêu',
    bloodPressure: 'Huyết áp',
    bloodPressureDescription: 'Ưu tiên các kiểm tra liên quan đến natri.',
    cholesterol: 'Cholesterol',
    cholesterolDescription: 'Ưu tiên các kiểm tra theo xu hướng chất xơ.',
    bloodGlucose: 'Đường huyết',
    bloodGlucoseDescription:
      'Được lưu ngay; các quy tắc an toàn về tập luyện và carbohydrate sẽ có sau.',
    uricAcid: 'Axit uric / gout',
    uricAcidDescription:
      'Được lưu ngay; các quy tắc về nguy cơ purin sẽ có sau.',
    addFocus: 'Thêm',
    removeFocus: 'Bỏ',
    focusSuffix: 'mối quan tâm sức khỏe',
    sensitiveDataNotice:
      'Chưa nhập thông tin thuốc, triệu chứng hoặc ghi chú của bác sĩ tại đây. Các dữ liệu này cần luồng hồ sơ sức khỏe mã hóa sắp tới.',
  },
  onboarding: {
    eyebrow: 'Thiết lập hồ sơ',
    title: 'Lập kế hoạch theo cuộc sống thực của bạn',
    description:
      'Lưu những gì hữu ích cho việc lên kế hoạch bữa ăn và tập tại nhà. Bạn có thể lưu một phần rồi quay lại sau.',
    complete: 'Đã hoàn tất thông tin cơ bản để lập kế hoạch',
    inProgress: 'Đang thiết lập thông tin cơ bản',
    goal: 'Mục tiêu chính',
    height: 'Chiều cao (cm)',
    weight: 'Cân nặng hiện tại (kg)',
    age: 'Tuổi',
    sex: 'Giới tính dùng cho tính toán chuyển hóa',
    activity: 'Mức độ hoạt động thường ngày',
    training: 'Kinh nghiệm tập luyện',
    sleep: 'Số giờ ngủ thường ngày',
    days: 'Ngày có thể tập',
    equipment: 'Thiết bị hiện có',
    environments: 'Môi trường tập luyện',
    restrictions: 'Hạn chế tập luyện do bác sĩ chỉ định',
    preferences: 'Ưu tiên ăn uống',
    allergies: 'Dị ứng thực phẩm',
    contexts: 'Nội dung theo dõi sức khỏe',
    injuries: 'Vấn đề vận động hiện tại',
    symptoms: 'Triệu chứng hiện tại khi tập',
    preferenceOmnivore: 'Ăn đa dạng', preferenceVegetarian: 'Ăn chay', preferenceVegan: 'Thuần chay', preferencePescatarian: 'Ăn cá', preferenceHalal: 'Halal', preferenceLowSodium: 'Ít natri', preferenceLowPurine: 'Ít purin',
    allergyMilk: 'Sữa', allergyEgg: 'Trứng', allergyFish: 'Cá', allergyShellfish: 'Hải sản có vỏ', allergyPeanut: 'Đậu phộng', allergyTreeNut: 'Các loại hạt cây', allergySoy: 'Đậu nành', allergyWheat: 'Lúa mì', allergySesame: 'Mè',
    contextBloodPressure: 'Huyết áp', contextCholesterol: 'Cholesterol', contextBloodGlucose: 'Đường huyết', contextUricAcid: 'Axit uric',
    injuryBack: 'Đau lưng', injuryJoint: 'Đau khớp', injuryBalance: 'Lo ngại thăng bằng',
    symptomNone: 'Không có triệu chứng', symptomChest: 'Khó chịu ở ngực', symptomDizziness: 'Chóng mặt', symptomBreath: 'Khó thở',
    save: 'Lưu thiết lập hồ sơ',
    goalWeightLoss: 'Giảm cân',
    goalMaintain: 'Duy trì cân nặng',
    goalMuscleGain: 'Tăng cơ',
    goalFitness: 'Thể lực',
    goalHealthTracking: 'Theo dõi sức khỏe',
    sexFemale: 'Nữ', sexMale: 'Nam', sexNotSpecified: 'Không muốn nêu',
    activitySedentary: 'Ít vận động', activityLight: 'Hoạt động nhẹ', activityModerate: 'Hoạt động vừa', activityActive: 'Hoạt động nhiều', activityVeryActive: 'Hoạt động rất nhiều',
    trainingNew: 'Mới bắt đầu tập', trainingBeginner: 'Cơ bản', trainingRegular: 'Tập thường xuyên',
    dayMon: 'T2', dayTue: 'T3', dayWed: 'T4', dayThu: 'T5', dayFri: 'T6', daySat: 'T7', daySun: 'CN',
    equipmentBodyweight: 'Trọng lượng cơ thể', equipmentChair: 'Ghế', equipmentMat: 'Thảm tập', equipmentBicycle: 'Xe đạp', equipmentTreadmill: 'Máy chạy mini', equipmentBand: 'Dây kháng lực', equipmentDumbbells: 'Tạ tay', equipmentGym: 'Phòng gym',
    environmentHome: 'Tại nhà', environmentOutdoors: 'Ngoài trời', environmentGym: 'Phòng gym',
    restrictionIntensity: 'Tránh cường độ cao', restrictionResistance: 'Tránh tập kháng lực', restrictionImpact: 'Tránh bài tập va chạm', restrictionGlucose: 'Theo dõi đường huyết',
  },
  sensitiveNotes: {
    eyebrow: 'Ghi chú sức khỏe được mã hóa',
    title: 'Ghi chú riêng tư cho kế hoạch của bạn',
    description: 'Các ghi chú này được mã hóa trước khi lưu. Chúng không xuất hiện trong lời nhắc và không dùng để chẩn đoán hoặc thay đổi thuốc.',
    medication: 'Ghi chú về thuốc hoặc an toàn khi tập',
    clinician: 'Hướng dẫn của bác sĩ',
    symptoms: 'Ghi chú bổ sung về triệu chứng',
    save: 'Lưu ghi chú đã mã hóa',
    unavailable: 'Ghi chú sức khỏe được mã hóa chưa khả dụng cho đến khi khóa mã hóa phía máy chủ được cấu hình.',
  },
  safety: {
    notMedicalAdvice:
      'Thông tin này hỗ trợ sức khỏe tổng quát, không phải lời khuyên y tế.',
    reviewBeforeSaving:
      'Hãy kiểm tra các giá trị, khẩu phần giả định và nguồn trước khi lưu.',
    noAutomaticSaving: 'Không có gì được tự động lưu.',
    seekUrgentCare:
      'Hãy tìm hỗ trợ y tế khẩn cấp khi có triệu chứng nặng hoặc tình trạng cấp cứu.',
    stopTraining:
      'Dừng vận động nếu đau ngực, khó thở nhiều, ngất, chóng mặt đột ngột hoặc có triệu chứng mới đáng lo.',
    clinicianPriority:
      'Hãy làm theo hướng dẫn của bác sĩ. Mục tiêu và hạn chế do bác sĩ chỉ định luôn được ưu tiên.',
    noDiagnosis:
      'Các lựa chọn theo dõi và nhận xét về bữa ăn không phải chẩn đoán hay khuyến nghị điều trị.',
    sensitiveData:
      'Không nhập chi tiết thuốc, triệu chứng hoặc ghi chú của bác sĩ cho đến khi có hồ sơ sức khỏe được mã hóa.',
  },
};

export const copy: Record<Locale, ProductCopy> = {
  en: englishCopy,
  vi: vietnameseCopy,
};

export function isLocale(value: string | null | undefined): value is Locale {
  return (
    value !== undefined &&
    value !== null &&
    supportedLocales.includes(value as Locale)
  );
}

export function getCopy(locale: Locale | null | undefined): ProductCopy {
  return copy[locale && isLocale(locale) ? locale : 'en'];
}
