/** Shared, presentation-only English/Vietnamese product copy. */
export const supportedLocales = ['en', 'vi'] as const;
export type Locale = (typeof supportedLocales)[number];

export const localeMetadata: Record<
  Locale,
  { label: string; documentLang: string }
> = {
  en: { label: 'English', documentLang: 'en' },
  vi: { label: 'Tiếng Việt', documentLang: 'vi' },
};

const englishCopy = {
  app: {
    name: 'Nourishwell',
    tagline: 'Private nutrition and movement support',
    language: 'Language',
    changeLanguage: 'Change language',
  },
  nav: {
    today: 'Today',
    capture: 'Capture',
    coach: 'Coach',
    measurements: 'Measurements',
    workouts: 'Workouts',
    progress: 'Progress',
    settings: 'Settings',
    openNavigation: 'Open navigation',
    closeNavigation: 'Close navigation',
  },
  common: {
    back: 'Back',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    save: 'Save',
    saving: 'Saving…',
    edit: 'Edit',
    delete: 'Delete',
    retry: 'Try again',
    loading: 'Loading…',
    required: 'Required',
    optional: 'Optional',
    private: 'Private',
  },
  today: {
    confirmedOnly: 'Confirmed meal records only',
    title: 'Today, with clear evidence.',
    logMeal: 'Log a meal',
    calories: 'Calories',
    protein: 'Protein',
    fiber: 'Fiber',
    sodium: 'Sodium',
    remaining: 'remaining',
    noTarget: 'No daily target set',
    mealLog: 'Today’s meal log',
    confirmedEntries: 'Your confirmed entries',
    loadingRecords: 'Loading your private records…',
    evidenceTitle: 'Evidence stays visible.',
    evidenceDescription:
      'Each saved meal keeps its ingredients, serving assumption, estimate source, and confidence. Nothing is auto-saved.',
    guidanceTitle: 'Health guidance comes next',
    guidanceDescription:
      'Personal targets and clinician-approved rules will be connected after onboarding. Today’s starter targets are not medical advice.',
    emptyTitle: 'No meals confirmed today',
    emptyDescription:
      'Start with a short typed description. You can edit every estimate before saving.',
    captureMeal: 'Capture a meal',
    agenda: 'Private agenda',
    upcoming: 'Coming up',
    noAgenda: 'No active reminders yet.',
  },
  mealCapture: {
    eyebrow: 'Capture · review required',
    title: 'What did you have?',
    description:
      'Describe a meal, scan a barcode, or search a food composition database.',
    text: 'Text',
    barcode: 'Barcode',
    vietnamData: 'Vietnam data',
    usda: 'USDA',
    photo: 'Photo',
    photoType: 'Photo type',
    mealPhoto: 'Meal photo',
    labelPhoto: 'Nutrition label',
    selectPhoto: 'Choose a photo',
    storePhoto: 'Store privately',
    uploadingPhoto: 'Storing privately…',
    photoStored: 'Private photo stored',
    photoProviderNote: 'Photos are kept private for a short time and are never public. Extraction stays review-only.',
    photoExtractionPending: 'Extract food or label facts, then choose an item for the editable meal review.',
    extractPhoto: 'Extract photo',
    extractingPhoto: 'Extracting…',
    detectedFoods: 'Detected food or label items',
    extractionReviewNote: 'Select an item to continue to nutrition review. Extraction never saves a meal automatically.',
    deletePhoto: 'Delete photo',
    photoReviewTitle: 'Private photo review',
    photoReviewDescription: 'Choose a meal or nutrition-label photo. Nothing is analysed or saved as a meal automatically.',
    mealPlaceholder: 'For example: phở bò with extra herbs, no chili oil',
    barcodePlaceholder: 'Enter an 8–14 digit barcode',
    startScanner: 'Scan with camera',
    stopScanner: 'Stop camera',
    scannerHelp: 'Point the camera at a package barcode. You can always type it manually.',
    scannerUnavailable: 'Barcode scanning is not supported in this browser. Enter the barcode manually.',
    scannerPermissionError: 'We could not use your camera. Allow camera access or enter the barcode manually.',
    vietnamDishPlaceholder: 'For example: cơm gà',
    vietnamIngredientPlaceholder: 'For example: thịt gà',
    usdaPlaceholder: 'For example: chicken breast, broccoli',
    analyse: 'Analyse and review',
    analysing: 'Preparing review…',
    reviewTitle: 'Review before saving',
    emptyReviewTitle: 'Nothing is saved automatically',
    saveFood: 'Save food',
    saveRecipe: 'Save recipe',
    libraryTitle: 'Your saved foods',
    libraryDescription: 'Choose a previously confirmed food or recipe to start an editable meal review.',
    libraryEmpty: 'Save a reviewed food or recipe to reuse it here.',
    food: 'Food',
    recipe: 'Recipe',
    deleteSavedFood: 'Delete saved food',
    deleteSavedConfirm: 'Delete this saved food or recipe permanently? This cannot be undone.',
    emptyReviewDescription:
      'Analyse a meal, inspect the ingredients and values, then confirm it yourself.',
    confidence: 'confidence',
    confirmMeal: 'Confirm meal',
    discardReview: 'Discard review',
    servingAssumption: 'Serving assumption',
    ingredients: 'Ingredients',
    source: 'Source',
    estimate: 'Estimate',
    manualEntry: 'Manual entry',
    reviewRequired: 'Review required before saving.',
    vietnamDish: 'Dish / Món ăn',
    vietnamIngredient: 'Ingredient / Thực phẩm',
    vietnamSearchLabel: 'Vietnam nutrition catalog search',
    usdaSearchLabel: 'USDA food search',
    typedProviderNote:
      'Typed meals use transparent starter rules. Always review the values.',
    barcodeProviderNote:
      'Barcode lookup uses Open Food Facts product data. The product label and your confirmation take priority.',
    vietnamProviderNote:
      'Vietnam nutrition catalog values are database-derived. Review the match and your serving before saving.',
    usdaProviderNote:
      'USDA FoodData Central uses a 100 g database basis and requires a private API key. Review the food and serving before saving.',
    reviewPlaceholder: 'Your meal will appear here',
    detectedIngredients: 'Detected ingredients',
    ingredientsPlaceholder: 'For example: rice noodles, beef, broth, herbs',
    ingredientsHelp: 'Separate ingredients with commas. This changes only this review before you confirm.',
    additionalNutrients: 'Additional nutrients reported by the source',
    additionalNutrientsSource: 'Only nutrients returned by the source are shown. Missing nutrients are unavailable, not zero.',
    ruleLabel: 'Rule',
    carbohydrates: 'Carbohydrates', totalSugar: 'Total sugar', addedSugar: 'Added sugar', totalFat: 'Total fat', saturatedFat: 'Saturated fat', cholesterol: 'Cholesterol', potassium: 'Potassium', calcium: 'Calcium', iron: 'Iron', alcohol: 'Alcohol', water: 'Water',
    serving: 'Serving',
    sourceAndReview: 'Source and review note',
    conditionChecks: 'Condition-specific checks',
    conditionChecksDescription:
      'Versioned tracking rules—not diagnoses or medical advice. They do not alter the nutrient values above.',
    discard: 'Discard',
    confirmAndSave: 'Confirm & save',
  },
  measurements: {
    eyebrow: 'Measurements',
    title: 'Track a measurement',
    description:
      'Enter a value you measured yourself. Review it before saving.',
    add: 'Add measurement',
    metric: 'Measurement type',
    customLabel: 'Lab test name',
    customLabelPlaceholder: 'For example: Vitamin D',
    value: 'Value',
    secondaryValue: 'Second value',
    systolic: 'Systolic',
    diastolic: 'Diastolic',
    unit: 'Unit',
    unitPlaceholder: 'For example: ng/mL',
    measuredAt: 'Measured at',
    saveMeasurement: 'Save measurement',
    reportTitle: 'Extract a report photo',
    reportDescription: 'Upload a report photo privately, then choose and edit an extracted value before saving.',
    extractReport: 'Extract report',
    extractingReport: 'Extracting…',
    reportStored: 'Private report stored temporarily.',
    reportReview: 'Choose a value to fill the editable form',
    retainReportTitle: 'Keep this report image privately',
    retainReportDescription: 'Off by default. If you save this confirmed value without selecting this, the source image is deleted. You can delete a retained image later; the confirmed measurement stays.',
    deleteRetainedReport: 'Delete retained report image',
    emptyTitle: 'No measurements yet',
    emptyDescription: 'Your confirmed measurements will appear here.',
    metrics: {
      weight: 'Weight',
      bloodPressure: 'Blood pressure',
      bloodGlucose: 'Blood glucose',
      totalCholesterol: 'Total cholesterol',
      uricAcid: 'Uric acid',
      customLab: 'Custom lab result',
    },
  },
  workouts: {
    eyebrow: 'Movement safety',
    title: 'Workout readiness',
    description:
      'Complete this screen before the app can generate a workout plan. It does not replace medical advice.',
    screeningTitle: 'Tell us what applies today',
    screeningDescription:
      'Select every statement that applies. Any selection pauses new plan generation for professional review.',
    chestPain: 'Chest pain, pressure, or tightness with activity',
    faintingOrDizziness: 'Fainting, new severe dizziness, or confusion',
    severeShortnessOfBreath: 'Unusual or severe shortness of breath',
    irregularHeartbeat: 'A fast or irregular heartbeat with activity',
    clinicianRestriction: 'A clinician has told me to avoid or restrict exercise',
    exerciseGlucoseRisk:
      'I use insulin or a medicine that can lower glucose and do not have an exercise plan from my care team',
    confirm: 'Confirm workout readiness',
    clearedTitle: 'Readiness confirmed',
    clearedDescription:
      'No gate flags were reported. A future plan will still use your equipment, recovery, and clinician restrictions.',
    pausedTitle: 'Workout plan paused',
    pausedDescription:
      'Do not start a new program from this app until the reported concern is reviewed by an appropriate clinician. Seek urgent care for severe or emergency symptoms.',
    incompleteTitle: 'Readiness required',
    incompleteDescription:
      'A workout plan cannot be generated until you complete this safety screen.',
    catalogTitle: 'Starter exercise library',
    catalogDescription:
      'These movements are a transparent starter catalog, not a workout prescription. A future plan will choose only compatible options.',
    catalogEmpty: 'The exercise catalog is temporarily unavailable. Retry loading your private records.',
    technique: 'Technique',
    regression: 'Make it easier',
    progression: 'Progress later',
    equipment: 'Equipment',
    planTitle: 'Your starter week',
    previewPlan: 'Generate plan preview',
    confirmPlan: 'Confirm this plan',
    planPreviewNote:
      'Review this conservative plan before saving. It is intentionally not adapted to symptoms, recovery, or equipment changes yet.',
    confirmedPlanNote:
      'Confirmed plan. Log completion and recovery in the upcoming workout-log flow.',
    minutes: 'minutes',
    effort: 'Effort',
    warmup: 'Warm-up',
    cooldown: 'Cooldown',
    rest: 'Rest',
    progressionCriteria: 'Progression',
    logTitle: 'Log a completed session',
    session: 'Session',
    duration: 'Actual duration',
    enjoyment: 'Enjoyment',
    pain: 'I had pain during this session',
    concerningSymptoms: 'I had concerning symptoms during this session',
    preGlucose: 'Before-exercise glucose (optional, mmol/L)',
    postGlucose: 'After-exercise glucose (optional, mmol/L)',
    saveLog: 'Save workout log',
    safetyLogNote:
      'Pain or concerning symptoms save this session as stopped for safety and pause future progression.',
    logHistory: 'Recent workout logs',
    noLogs: 'No completed workout sessions have been logged yet.',
    sets: 'Sets',
    reps: 'Reps per set',
    load: 'Load (optional)',
    heartRate: 'Average heart rate (optional)',
    checkin: 'Run recovery check-in',
    checkinTitle: 'Weekly check-in',
    checkinMaintain: 'Maintain the current plan; no automatic progression is applied.',
    checkinRepeat: 'Repeat the current plan before changing it; adherence is still building.',
    checkinHold: 'Hold progression and review the reported safety concern with an appropriate clinician.',
  },
  progress: {
    eyebrow: 'Progress overview',
    title: 'Your recent records',
    description: 'A private summary of confirmed records from the last 30 days. Patterns are observations, not proof that one thing caused another.',
    coverage: 'Data coverage',
    daysWithData: 'days with data',
    completedWorkouts: 'Completed workouts',
    safetyStopped: 'Stopped for safety',
    safetyStoppedNote: 'Review pain or concerning symptoms before progressing.',
    latestNutrition: 'Latest nutrition day',
    meals: 'meals',
    noNutrition: 'No confirmed nutrition records yet.',
    nutritionDays: 'Recent nutrition days',
    nutritionDaysDescription: 'Confirmed meal totals only; missing days are not treated as zero intake.',
    measurementTrends: 'Measurement changes',
    trendWarning: 'Changes are descriptive, non-causal observations. Sample size is shown for context.',
    noMeasurements: 'No confirmed measurements in this period.',
  },
  coach: {
    eyebrow: 'Daily coach',
    title: 'A calm next step for today.',
    description: 'Private guidance from your confirmed day totals, active health focuses, and saved plan. It does not diagnose, change records, or replace clinician guidance.',
    boundaryTitle: 'Facts first, confirmation always',
    boundaryDescription: 'This starter coach only compares confirmed tracking data with your effective targets. Future chat suggestions must remain reviewable before any record changes.',
    remaining: 'Remaining today',
    prioritiesTitle: 'What to prioritize',
    prioritiesDescription: 'These are tracking prompts, not medical treatment instructions.',
    planTitle: 'Movement plan',
    planDescription: 'Your confirmed plan is separate from this guidance and is never changed automatically.',
    planAvailable: 'Your confirmed plan has {count} scheduled sessions to review when you are ready.',
    noPlan: 'Complete readiness and confirm a plan before using workout guidance.',
    priorities: {
      protein: 'You still have protein remaining in your personal daily target. If it fits your preferences and plan, consider a protein-containing choice and record the actual serving.',
      fiber: 'You still have fiber remaining in your personal daily target. Consider a food pattern that includes vegetables, beans, fruit, or whole grains when appropriate for you.',
      sodium: 'Your confirmed sodium total has reached your personal daily target. For the rest of today, compare sauces, broth, seasoning, and packaged labels before deciding what fits.',
      healthFocus: 'Keep your selected health focus visible when reviewing meals and measurements. Use clinician-defined targets or restrictions whenever they are available.',
      balanced: 'No target comparison needs attention yet. Continue logging confirmed meals, measurements, and workouts so your private records stay useful.',
    },
  },
  reminders: {
    title: 'Private agenda reminders',
    description: 'Schedules stay in your private agenda. Future lock-screen notifications will use neutral text only.',
    kind: 'Reminder type',
    time: 'Time (Asia/Bangkok)',
    days: 'Repeat on',
    save: 'Save reminder',
    saving: 'Saving reminder…',
    noReminders: 'No reminders saved yet.',
    next: 'Next',
    meal: 'Meal check-in',
    workout: 'Workout',
    measurement: 'Measurement',
    weeklyReview: 'Weekly review',
    pause: 'Pause',
    resume: 'Resume',
    update: 'Update reminder',
    snoozeHour: 'Snooze 1 hour',
    quietHours: 'Quiet hours',
    quietStart: 'Starts',
    quietEnd: 'Ends',
    delete: 'Delete',
    paused: 'Paused',
    deleteConfirm: 'Delete this reminder permanently? This cannot be undone.',
  },
  settings: {
    eyebrow: 'Settings',
    title: 'Personal targets',
    description:
      'Use targets you set for yourself. Clinician-defined targets always take priority.',
    calories: 'Calories',
    protein: 'Protein',
    fiber: 'Fiber',
    sodium: 'Sodium',
    saveTargets: 'Save personal targets',
    healthFocuses: 'Health focuses',
    healthFocusDescription: 'Optional tracking preferences, not diagnoses.',
    saveHealthFocuses: 'Save health focuses',
    dataPrivacy: 'Privacy and data',
    exportData: 'Export my data',
    exportDescription: 'Download selected confirmed meal, measurement, and workout records as a private CSV. No sharing link is created.',
    exportStart: 'Start date',
    exportEnd: 'End date',
    exportCsv: 'Download CSV',
    exportPdf: 'Download PDF report',
    exportFullArchive: 'Download full archive',
    exportFullArchiveDescription: 'Downloads all private structured records and current private uploads in a versioned JSON file. Keep this archive secure; it may contain sensitive health information.',
    deleteData: 'Delete my data',
    deleteDataDescription: 'Permanently deletes every private meal, measurement, workout, reminder, profile record, extraction record, and uploaded image. This cannot be undone.',
    deleteDataPrompt: 'Type DELETE MY DATA to enable permanent deletion',
    deletingData: 'Deleting private data…',
    deleteDataError: 'We could not permanently delete your private data.',
    targetsDescription:
      'These targets guide the Today dashboard only; they are not medical advice.',
    targetSuffix: 'target',
    bloodPressure: 'Blood pressure',
    bloodPressureDescription: 'Prioritize sodium-related review checks.',
    cholesterol: 'Cholesterol',
    cholesterolDescription: 'Prioritize fiber-pattern review checks.',
    bloodGlucose: 'Blood glucose',
    bloodGlucoseDescription:
      'Saved now; exercise and carbohydrate safety rules come later.',
    uricAcid: 'Uric acid / gout',
    uricAcidDescription: 'Saved now; purine-risk rules come later.',
    addFocus: 'Add',
    removeFocus: 'Remove',
    focusSuffix: 'health focus',
    sensitiveDataNotice:
      'Do not enter medication, symptoms, or clinician notes here yet. Those need the upcoming encrypted health-profile flow.',
  },
  onboarding: {
    eyebrow: 'Profile setup',
    title: 'Plan around your real life',
    description:
      'Save what is useful for meal and home-workout planning. You can save a partial setup and return later.',
    complete: 'Planning basics complete',
    inProgress: 'Planning basics in progress',
    goal: 'Primary goal',
    height: 'Height (cm)',
    weight: 'Current weight (kg)',
    age: 'Age',
    sex: 'Sex for metabolic calculations',
    activity: 'Usual activity',
    training: 'Training history',
    sleep: 'Typical sleep (hours)',
    days: 'Available training days',
    equipment: 'Equipment available now',
    environments: 'Training environments',
    restrictions: 'Clinician exercise restrictions',
    preferences: 'Food preferences',
    allergies: 'Food allergies',
    contexts: 'Health tracking contexts',
    injuries: 'Current movement concerns',
    symptoms: 'Current exercise symptoms',
    preferenceOmnivore: 'Omnivore', preferenceVegetarian: 'Vegetarian', preferenceVegan: 'Vegan', preferencePescatarian: 'Pescatarian', preferenceHalal: 'Halal', preferenceLowSodium: 'Lower sodium', preferenceLowPurine: 'Lower purine',
    allergyMilk: 'Milk', allergyEgg: 'Egg', allergyFish: 'Fish', allergyShellfish: 'Shellfish', allergyPeanut: 'Peanut', allergyTreeNut: 'Tree nuts', allergySoy: 'Soy', allergyWheat: 'Wheat', allergySesame: 'Sesame',
    contextBloodPressure: 'Blood pressure', contextCholesterol: 'Cholesterol', contextBloodGlucose: 'Blood glucose', contextUricAcid: 'Uric acid',
    injuryBack: 'Back pain', injuryJoint: 'Joint pain', injuryBalance: 'Balance concern',
    symptomNone: 'No symptoms', symptomChest: 'Chest discomfort', symptomDizziness: 'Dizziness', symptomBreath: 'Shortness of breath',
    save: 'Save profile setup',
    goalWeightLoss: 'Weight loss',
    goalMaintain: 'Maintain weight',
    goalMuscleGain: 'Muscle gain',
    goalFitness: 'Fitness',
    goalHealthTracking: 'Health tracking',
    sexFemale: 'Female',
    sexMale: 'Male',
    sexNotSpecified: 'Prefer not to specify',
    activitySedentary: 'Mostly sitting',
    activityLight: 'Lightly active',
    activityModerate: 'Moderately active',
    activityActive: 'Active',
    activityVeryActive: 'Very active',
    trainingNew: 'New to exercise',
    trainingBeginner: 'Beginner',
    trainingRegular: 'Regular training',
    dayMon: 'Mon', dayTue: 'Tue', dayWed: 'Wed', dayThu: 'Thu', dayFri: 'Fri', daySat: 'Sat', daySun: 'Sun',
    equipmentBodyweight: 'Bodyweight', equipmentChair: 'Chair', equipmentMat: 'Exercise mat', equipmentBicycle: 'Bicycle', equipmentTreadmill: 'Mini treadmill', equipmentBand: 'Resistance band', equipmentDumbbells: 'Dumbbells', equipmentGym: 'Gym',
    environmentHome: 'Home', environmentOutdoors: 'Outdoors', environmentGym: 'Gym',
    restrictionIntensity: 'Avoid high intensity', restrictionResistance: 'Avoid resistance training', restrictionImpact: 'Avoid impact exercise', restrictionGlucose: 'Monitor glucose',
  },
  sensitiveNotes: {
    eyebrow: 'Encrypted health notes',
    title: 'Private notes for your plan',
    description: 'These notes are encrypted before storage. They are not shown in reminders or used to diagnose or change medication.',
    medication: 'Medication or exercise-safety notes',
    clinician: 'Clinician instructions',
    symptoms: 'Additional symptom notes',
    save: 'Save encrypted notes',
    unavailable: 'Encrypted health notes are unavailable until the server-side encryption key is configured.',
  },
  feedback: {
    targetsSaveError: 'We could not save your targets.',
    targetsReplayed: 'Your earlier target change was already saved.',
    targetsSaved: 'Personal targets saved. Clinician-defined targets remain in effect where present.',
    focusesSaveError: 'We could not save your health focuses.',
    focusesReplayed: 'Your earlier health-focus change was already saved.',
    focusesSaved: 'Health focuses saved. Future meal reviews will prioritize the selected checks.',
    onboardingSaveError: 'We could not save your profile setup.',
    onboardingReplayed: 'Your earlier profile setup was already saved.',
    onboardingComplete: 'Profile setup saved. Review workout readiness before starting a plan.',
    onboardingSaved: 'Profile setup saved. You can finish the remaining planning basics anytime.',
    notesSaveError: 'We could not save encrypted health notes.',
    notesSaved: 'Encrypted health notes saved to your private profile.',
    reportStoreError: 'The report could not be stored privately.',
    reportExtractError: 'The report could not be extracted.',
    measurementBloodPressureError: 'Enter both positive blood pressure values.',
    measurementCustomLabError: 'Name the lab result and enter its unit.',
    measurementValueError: 'Enter a positive measurement value.',
    measurementSaveError: 'We could not save this measurement.',
    measurementReplayed: 'Your earlier measurement was already recorded.',
    measurementSaved: 'Confirmed measurement saved to your private history.',
    measurementDeleteImageError: 'We could not delete this source image.',
    readinessSaveError: 'We could not save workout readiness.',
    readinessCleared: 'Workout readiness confirmed. A plan can be considered after you choose your equipment and availability.',
    readinessPaused: 'Workout-plan generation is paused until you review the reported safety concern with an appropriate clinician.',
    planPreviewError: 'We could not generate a workout-plan preview.',
    planConfirmError: 'We could not confirm this workout plan.',
    planReplayed: 'Your earlier workout-plan confirmation was already recorded.',
    planConfirmed: 'Workout plan confirmed. Keep the intensity easy and stop for concerning symptoms.',
    checkinError: 'We could not complete the recovery check-in.',
    workoutLogValidation: 'Enter valid duration, effort, enjoyment, and optional glucose values.',
    workoutLogSaveError: 'We could not save this workout log.',
    workoutLogReview: 'Workout log saved. Do not progress your plan; review the reported pain or symptoms with an appropriate clinician.',
    workoutLogSaved: 'Workout completion saved to your private history.',
    mealReviewError: 'We could not prepare a review.',
    mealReviewIncomplete: 'The meal review was incomplete. Please try again.',
    mealSaveError: 'We could not save this meal.',
    mealReplayed: 'Your earlier save was already recorded.',
    mealSaved: 'Meal saved. Today’s totals are now based on your confirmed entry.',
    savedFoodSaveError: 'We could not save this personal food.',
    savedFoodReplayed: 'Your personal food was already saved.',
    recipeSaved: 'Recipe saved to your private food library.',
    foodSaved: 'Food saved to your private food library.',
    savedFoodDeleted: 'Saved food deleted from your private library.',
    savedFoodDeleteError: 'We could not delete this saved food.',
    personalFoodReview: 'Using your previously confirmed food. Review it again before saving this meal.',
    photoStoreError: 'The photo could not be stored privately.',
    photoDeleteError: 'The private upload could not be deleted. Please try again.',
    photoExtractError: 'The image could not be extracted.',
    reminderDaysRequired: 'Choose at least one day.',
    reminderSaveError: 'We could not save this reminder.',
    loadMealsError: 'We could not load today’s meals.',
    reminderUpdateError: 'We could not update this reminder.',
    reminderSaved: 'Reminder saved to your private agenda.',
    reminderDeleted: 'Reminder deleted.',
    reminderPaused: 'Reminder paused.',
    reminderResumed: 'Reminder resumed.',
    reminderSnoozed: 'Reminder snoozed.',
    reminderRescheduled: 'Reminder rescheduled.',
    reportImageDeleted: 'Private report image deleted. The confirmed measurement remains.',
    accountDeleteError: 'We could not permanently delete your private data.',
    accountDeleted: 'Your private Nourishwell data has been permanently deleted.',
    localeSaveError: 'We could not save your language preference.',
    dashboardOffline: 'You are offline. Previously loaded information stays visible, but health records cannot be changed until you reconnect.',
    dashboardPermissionDenied: 'Your private records could not be opened. Sign in again, then retry.',
    dashboardRetry: 'Retry loading private records',
    exportDateRange: 'Choose a valid date range.',
    exportCreateError: 'We could not create this export.',
  },
  safety: {
    notMedicalAdvice:
      'This information is for general wellness support and is not medical advice.',
    reviewBeforeSaving:
      'Review values, serving assumptions, and sources before saving.',
    noAutomaticSaving: 'Nothing is saved automatically.',
    seekUrgentCare:
      'Seek urgent medical care for severe symptoms or an emergency.',
    stopTraining:
      'Stop activity if you have chest pain, severe shortness of breath, fainting, sudden dizziness, or concerning new symptoms.',
    clinicianPriority:
      'Follow your clinician’s advice. Clinician-defined targets and restrictions take priority.',
    noDiagnosis:
      'Tracking preferences and meal findings are not diagnoses or treatment recommendations.',
    sensitiveData:
      'Do not enter medication details, symptoms, or clinician notes until the encrypted health-profile flow is available.',
  },
} as const;

type StringLeafShape<T> = T extends string
  ? string
  : { [Key in keyof T]: StringLeafShape<T[Key]> };

/** The stable key structure every supported locale must provide. */
export type ProductCopy = StringLeafShape<typeof englishCopy>;

const vietnameseCopy: ProductCopy = {
  app: {
    name: 'Nourishwell',
    tagline: 'Hỗ trợ riêng tư về dinh dưỡng và vận động',
    language: 'Ngôn ngữ',
    changeLanguage: 'Đổi ngôn ngữ',
  },
  nav: {
    today: 'Hôm nay',
    capture: 'Ghi bữa ăn',
    coach: 'Huấn luyện viên',
    measurements: 'Chỉ số',
    workouts: 'Tập luyện',
    progress: 'Tiến độ',
    settings: 'Cài đặt',
    openNavigation: 'Mở điều hướng',
    closeNavigation: 'Đóng điều hướng',
  },
  common: {
    back: 'Quay lại',
    cancel: 'Hủy',
    close: 'Đóng',
    confirm: 'Xác nhận',
    save: 'Lưu',
    saving: 'Đang lưu…',
    edit: 'Chỉnh sửa',
    delete: 'Xóa',
    retry: 'Thử lại',
    loading: 'Đang tải…',
    required: 'Bắt buộc',
    optional: 'Tùy chọn',
    private: 'Riêng tư',
  },
  today: {
    confirmedOnly: 'Chỉ các bữa ăn đã xác nhận',
    title: 'Hôm nay, với thông tin rõ ràng.',
    logMeal: 'Ghi bữa ăn',
    calories: 'Năng lượng',
    protein: 'Chất đạm',
    fiber: 'Chất xơ',
    sodium: 'Natri',
    remaining: 'còn lại',
    noTarget: 'Chưa đặt mục tiêu hằng ngày',
    mealLog: 'Nhật ký bữa ăn hôm nay',
    confirmedEntries: 'Các mục đã xác nhận',
    loadingRecords: 'Đang tải dữ liệu riêng tư của bạn…',
    evidenceTitle: 'Thông tin nguồn luôn hiển thị.',
    evidenceDescription:
      'Mỗi bữa ăn đã lưu giữ lại nguyên liệu, khẩu phần giả định, nguồn ước tính và độ tin cậy. Không có gì được tự động lưu.',
    guidanceTitle: 'Hướng dẫn sức khỏe sẽ có tiếp theo',
    guidanceDescription:
      'Mục tiêu cá nhân và các quy tắc được bác sĩ chấp thuận sẽ được kết nối sau phần thiết lập ban đầu. Các mục tiêu mẫu hôm nay không phải lời khuyên y tế.',
    emptyTitle: 'Hôm nay chưa có bữa ăn nào được xác nhận',
    emptyDescription:
      'Bắt đầu bằng một mô tả ngắn. Bạn có thể chỉnh sửa mọi ước tính trước khi lưu.',
    captureMeal: 'Ghi bữa ăn',
    agenda: 'Lịch riêng tư',
    upcoming: 'Sắp tới',
    noAgenda: 'Chưa có nhắc việc đang hoạt động.',
  },
  mealCapture: {
    eyebrow: 'Ghi nhận · cần xem lại',
    title: 'Bạn đã ăn gì?',
    description:
      'Mô tả bữa ăn, quét mã vạch hoặc tìm trong cơ sở dữ liệu thành phần thực phẩm.',
    text: 'Nhập món ăn',
    barcode: 'Mã vạch',
    vietnamData: 'Dữ liệu Việt Nam',
    usda: 'USDA',
    photo: 'Ảnh',
    photoType: 'Loại ảnh',
    mealPhoto: 'Ảnh bữa ăn',
    labelPhoto: 'Nhãn dinh dưỡng',
    selectPhoto: 'Chọn ảnh',
    storePhoto: 'Lưu riêng tư',
    uploadingPhoto: 'Đang lưu riêng tư…',
    photoStored: 'Đã lưu ảnh riêng tư',
    photoProviderNote: 'Ảnh được giữ riêng tư trong thời gian ngắn và không bao giờ công khai. Trích xuất luôn cần được xem lại.',
    photoExtractionPending: 'Trích xuất thông tin món ăn hoặc nhãn, sau đó chọn một mục để xem lại bữa ăn có thể chỉnh sửa.',
    extractPhoto: 'Trích xuất từ ảnh',
    extractingPhoto: 'Đang trích xuất…',
    detectedFoods: 'Món ăn hoặc mục nhãn đã nhận diện',
    extractionReviewNote: 'Chọn một mục để tiếp tục xem lại dinh dưỡng. Trích xuất không tự động lưu bữa ăn.',
    deletePhoto: 'Xóa ảnh',
    photoReviewTitle: 'Xem lại ảnh riêng tư',
    photoReviewDescription: 'Chọn ảnh bữa ăn hoặc nhãn dinh dưỡng. Không có gì được phân tích hay lưu thành bữa ăn tự động.',
    mealPlaceholder: 'Ví dụ: phở bò thêm rau thơm, không dầu ớt',
    barcodePlaceholder: 'Nhập mã vạch gồm 8–14 chữ số',
    startScanner: 'Quét bằng camera',
    stopScanner: 'Dừng camera',
    scannerHelp: 'Hướng camera vào mã vạch trên bao bì. Bạn luôn có thể nhập thủ công.',
    scannerUnavailable: 'Trình duyệt này không hỗ trợ quét mã vạch. Hãy nhập mã vạch thủ công.',
    scannerPermissionError: 'Không thể dùng camera. Hãy cho phép dùng camera hoặc nhập mã vạch thủ công.',
    vietnamDishPlaceholder: 'Ví dụ: cơm gà',
    vietnamIngredientPlaceholder: 'Ví dụ: thịt gà',
    usdaPlaceholder: 'Ví dụ: ức gà, bông cải xanh',
    analyse: 'Phân tích và xem lại',
    analysing: 'Đang chuẩn bị bản xem lại…',
    reviewTitle: 'Xem lại trước khi lưu',
    emptyReviewTitle: 'Không có gì được tự động lưu',
    saveFood: 'Lưu món ăn',
    saveRecipe: 'Lưu công thức',
    libraryTitle: 'Món ăn đã lưu',
    libraryDescription: 'Chọn món ăn hoặc công thức đã xác nhận trước đó để bắt đầu xem lại bữa ăn có thể chỉnh sửa.',
    libraryEmpty: 'Lưu món ăn hoặc công thức đã xem lại để dùng lại ở đây.',
    food: 'Món ăn',
    recipe: 'Công thức',
    deleteSavedFood: 'Xóa món ăn đã lưu',
    deleteSavedConfirm: 'Xóa vĩnh viễn món ăn hoặc công thức này? Không thể hoàn tác.',
    emptyReviewDescription:
      'Phân tích bữa ăn, kiểm tra nguyên liệu và các giá trị, rồi tự bạn xác nhận.',
    confidence: 'độ tin cậy',
    confirmMeal: 'Xác nhận bữa ăn',
    discardReview: 'Bỏ bản xem lại',
    servingAssumption: 'Khẩu phần giả định',
    ingredients: 'Nguyên liệu',
    source: 'Nguồn',
    estimate: 'Ước tính',
    manualEntry: 'Nhập thủ công',
    reviewRequired: 'Cần xem lại trước khi lưu.',
    vietnamDish: 'Món ăn / Dish',
    vietnamIngredient: 'Thực phẩm / Ingredient',
    vietnamSearchLabel: 'Tìm kiếm trong cơ sở dữ liệu dinh dưỡng Việt Nam',
    usdaSearchLabel: 'Tìm kiếm thực phẩm USDA',
    typedProviderNote:
      'Các bữa ăn nhập chữ dùng quy tắc khởi đầu minh bạch. Luôn kiểm tra lại các giá trị.',
    barcodeProviderNote:
      'Tra mã vạch dùng dữ liệu sản phẩm Open Food Facts. Nhãn sản phẩm và xác nhận của bạn được ưu tiên.',
    vietnamProviderNote:
      'Giá trị từ cơ sở dữ liệu dinh dưỡng Việt Nam. Hãy kiểm tra món khớp và khẩu phần trước khi lưu.',
    usdaProviderNote:
      'USDA FoodData Central dùng cơ sở dữ liệu theo 100 g và cần khóa API riêng tư. Hãy kiểm tra thực phẩm và khẩu phần trước khi lưu.',
    reviewPlaceholder: 'Bữa ăn của bạn sẽ xuất hiện ở đây',
    detectedIngredients: 'Nguyên liệu được nhận diện',
    ingredientsPlaceholder: 'Ví dụ: bún gạo, thịt bò, nước dùng, rau thơm',
    ingredientsHelp: 'Ngăn cách nguyên liệu bằng dấu phẩy. Thay đổi này chỉ áp dụng cho bản xem lại trước khi bạn xác nhận.',
    additionalNutrients: 'Dưỡng chất bổ sung do nguồn cung cấp',
    additionalNutrientsSource: 'Chỉ những dưỡng chất nguồn trả về mới được hiển thị. Dưỡng chất thiếu nghĩa là chưa có dữ liệu, không phải bằng 0.',
    ruleLabel: 'Quy tắc',
    carbohydrates: 'Carbohydrate', totalSugar: 'Tổng đường', addedSugar: 'Đường bổ sung', totalFat: 'Tổng chất béo', saturatedFat: 'Chất béo bão hòa', cholesterol: 'Cholesterol', potassium: 'Kali', calcium: 'Canxi', iron: 'Sắt', alcohol: 'Cồn', water: 'Nước',
    serving: 'Khẩu phần',
    sourceAndReview: 'Nguồn và ghi chú xem lại',
    conditionChecks: 'Kiểm tra theo tình trạng',
    conditionChecksDescription:
      'Các quy tắc theo dõi có phiên bản — không phải chẩn đoán hay lời khuyên y tế. Chúng không thay đổi giá trị dinh dưỡng ở trên.',
    discard: 'Bỏ',
    confirmAndSave: 'Xác nhận và lưu',
  },
  measurements: {
    eyebrow: 'Chỉ số',
    title: 'Theo dõi chỉ số',
    description: 'Nhập giá trị bạn tự đo. Hãy xem lại trước khi lưu.',
    add: 'Thêm chỉ số',
    metric: 'Loại chỉ số',
    customLabel: 'Tên xét nghiệm',
    customLabelPlaceholder: 'Ví dụ: Vitamin D',
    value: 'Giá trị',
    secondaryValue: 'Giá trị thứ hai',
    systolic: 'Tâm thu',
    diastolic: 'Tâm trương',
    unit: 'Đơn vị',
    unitPlaceholder: 'Ví dụ: ng/mL',
    measuredAt: 'Thời điểm đo',
    saveMeasurement: 'Lưu chỉ số',
    reportTitle: 'Trích xuất ảnh báo cáo',
    reportDescription: 'Tải riêng tư ảnh báo cáo, sau đó chọn và chỉnh sửa giá trị trước khi lưu.',
    extractReport: 'Trích xuất báo cáo',
    extractingReport: 'Đang trích xuất…',
    reportStored: 'Ảnh báo cáo riêng tư được lưu tạm thời.',
    reportReview: 'Chọn một giá trị để điền vào biểu mẫu có thể chỉnh sửa',
    retainReportTitle: 'Giữ riêng tư ảnh báo cáo này',
    retainReportDescription: 'Mặc định tắt. Nếu lưu giá trị đã xác nhận mà không chọn mục này, ảnh nguồn sẽ bị xóa. Bạn có thể xóa ảnh đã giữ sau; chỉ số đã xác nhận vẫn được giữ.',
    deleteRetainedReport: 'Xóa ảnh báo cáo đã giữ',
    emptyTitle: 'Chưa có chỉ số nào',
    emptyDescription: 'Các chỉ số bạn xác nhận sẽ xuất hiện ở đây.',
    metrics: {
      weight: 'Cân nặng',
      bloodPressure: 'Huyết áp',
      bloodGlucose: 'Đường huyết',
      totalCholesterol: 'Cholesterol toàn phần',
      uricAcid: 'Axit uric',
      customLab: 'Kết quả xét nghiệm khác',
    },
  },
  workouts: {
    eyebrow: 'An toàn vận động',
    title: 'Sẵn sàng tập luyện',
    description:
      'Hoàn thành phần này trước khi ứng dụng có thể tạo kế hoạch tập. Phần này không thay thế lời khuyên y tế.',
    screeningTitle: 'Cho biết điều nào đúng với bạn hôm nay',
    screeningDescription:
      'Chọn tất cả điều phù hợp. Bất kỳ lựa chọn nào cũng sẽ tạm dừng tạo kế hoạch mới để cần đánh giá chuyên môn.',
    chestPain: 'Đau, tức hoặc nặng ngực khi vận động',
    faintingOrDizziness: 'Ngất, chóng mặt nặng mới xuất hiện hoặc lú lẫn',
    severeShortnessOfBreath: 'Khó thở bất thường hoặc nghiêm trọng',
    irregularHeartbeat: 'Tim đập nhanh hoặc không đều khi vận động',
    clinicianRestriction: 'Bác sĩ đã yêu cầu tôi tránh hoặc hạn chế tập luyện',
    exerciseGlucoseRisk:
      'Tôi dùng insulin hoặc thuốc có thể làm hạ đường huyết và chưa có kế hoạch tập từ đội ngũ chăm sóc',
    confirm: 'Xác nhận sẵn sàng tập luyện',
    clearedTitle: 'Đã xác nhận sẵn sàng',
    clearedDescription:
      'Bạn không báo cáo cờ an toàn nào. Kế hoạch trong tương lai vẫn sẽ dùng thiết bị, hồi phục và hạn chế của bác sĩ.',
    pausedTitle: 'Đã tạm dừng kế hoạch tập',
    pausedDescription:
      'Không bắt đầu chương trình mới từ ứng dụng này cho đến khi vấn đề được báo cáo được chuyên gia phù hợp xem xét. Hãy tìm trợ giúp khẩn cấp khi có triệu chứng nặng hoặc cấp cứu.',
    incompleteTitle: 'Cần hoàn thành sàng lọc',
    incompleteDescription:
      'Không thể tạo kế hoạch tập cho đến khi bạn hoàn thành màn hình an toàn này.',
    catalogTitle: 'Thư viện bài tập khởi đầu',
    catalogDescription:
      'Các động tác này là danh mục khởi đầu minh bạch, không phải đơn tập. Kế hoạch trong tương lai chỉ chọn các lựa chọn phù hợp.',
    catalogEmpty: 'Danh mục bài tập tạm thời không khả dụng. Hãy tải lại hồ sơ riêng tư của bạn.',
    technique: 'Kỹ thuật',
    regression: 'Giảm độ khó',
    progression: 'Tiến triển sau',
    equipment: 'Dụng cụ',
    planTitle: 'Tuần khởi đầu của bạn',
    previewPlan: 'Tạo bản xem trước kế hoạch',
    confirmPlan: 'Xác nhận kế hoạch này',
    planPreviewNote:
      'Hãy xem lại kế hoạch thận trọng này trước khi lưu. Hiện kế hoạch chưa điều chỉnh theo triệu chứng, hồi phục hoặc thay đổi thiết bị.',
    confirmedPlanNote:
      'Kế hoạch đã xác nhận. Hãy ghi nhận hoàn thành và hồi phục trong luồng nhật ký tập sắp tới.',
    minutes: 'phút',
    effort: 'Cường độ',
    warmup: 'Khởi động',
    cooldown: 'Thả lỏng',
    rest: 'Nghỉ',
    progressionCriteria: 'Điều kiện tăng tiến',
    logTitle: 'Ghi nhận buổi tập đã hoàn thành',
    session: 'Buổi tập',
    duration: 'Thời lượng thực tế',
    enjoyment: 'Mức yêu thích',
    pain: 'Tôi bị đau trong buổi tập này',
    concerningSymptoms: 'Tôi có triệu chứng đáng lo trong buổi tập này',
    preGlucose: 'Đường huyết trước tập (tùy chọn, mmol/L)',
    postGlucose: 'Đường huyết sau tập (tùy chọn, mmol/L)',
    saveLog: 'Lưu nhật ký tập',
    safetyLogNote:
      'Đau hoặc triệu chứng đáng lo sẽ lưu buổi tập là dừng vì an toàn và tạm dừng tăng tiến trong tương lai.',
    logHistory: 'Nhật ký tập gần đây',
    noLogs: 'Chưa có buổi tập hoàn thành nào được ghi lại.',
    sets: 'Số hiệp',
    reps: 'Số lần mỗi hiệp',
    load: 'Tải trọng (tùy chọn)',
    heartRate: 'Nhịp tim trung bình (tùy chọn)',
    checkin: 'Thực hiện đánh giá hồi phục',
    checkinTitle: 'Đánh giá hằng tuần',
    checkinMaintain: 'Duy trì kế hoạch hiện tại; không tự động tăng tiến.',
    checkinRepeat: 'Lặp lại kế hoạch hiện tại trước khi thay đổi; mức tuân thủ vẫn đang xây dựng.',
    checkinHold: 'Tạm dừng tăng tiến và trao đổi vấn đề an toàn đã báo cáo với chuyên gia phù hợp.',
  },
  progress: {
    eyebrow: 'Tổng quan tiến độ',
    title: 'Các ghi nhận gần đây',
    description: 'Tóm tắt riêng tư các dữ liệu đã xác nhận trong 30 ngày qua. Mối liên hệ chỉ là quan sát, không chứng minh điều này gây ra điều kia.',
    coverage: 'Mức độ có dữ liệu',
    daysWithData: 'ngày có dữ liệu',
    completedWorkouts: 'Buổi tập hoàn thành',
    safetyStopped: 'Dừng vì an toàn',
    safetyStoppedNote: 'Xem lại đau hoặc triệu chứng đáng lo trước khi tăng tiến.',
    latestNutrition: 'Ngày dinh dưỡng gần nhất',
    meals: 'bữa ăn',
    noNutrition: 'Chưa có dữ liệu dinh dưỡng đã xác nhận.',
    nutritionDays: 'Các ngày dinh dưỡng gần đây',
    nutritionDaysDescription: 'Chỉ tổng các bữa ăn đã xác nhận; ngày thiếu dữ liệu không được coi là ăn bằng không.',
    measurementTrends: 'Thay đổi chỉ số',
    trendWarning: 'Các thay đổi chỉ có tính mô tả, không cho thấy quan hệ nhân quả. Cỡ mẫu được hiển thị để tham khảo.',
    noMeasurements: 'Chưa có chỉ số đã xác nhận trong giai đoạn này.',
  },
  coach: {
    eyebrow: 'Hướng dẫn hằng ngày',
    title: 'Một bước tiếp theo nhẹ nhàng cho hôm nay.',
    description: 'Hướng dẫn riêng tư từ tổng dữ liệu đã xác nhận trong ngày, các mối quan tâm sức khỏe đang chọn và kế hoạch đã lưu. Công cụ không chẩn đoán, không tự thay đổi dữ liệu và không thay thế hướng dẫn của chuyên gia.',
    boundaryTitle: 'Ưu tiên dữ liệu, luôn cần xác nhận',
    boundaryDescription: 'Phiên bản hướng dẫn ban đầu này chỉ so sánh dữ liệu theo dõi đã xác nhận với mục tiêu đang áp dụng. Các gợi ý trò chuyện sau này vẫn phải được xem lại trước khi thay đổi bất kỳ dữ liệu nào.',
    remaining: 'Còn lại hôm nay',
    prioritiesTitle: 'Điều nên ưu tiên',
    prioritiesDescription: 'Đây là gợi ý theo dõi, không phải chỉ dẫn điều trị y tế.',
    planTitle: 'Kế hoạch vận động',
    planDescription: 'Kế hoạch đã xác nhận tách biệt với hướng dẫn này và không bao giờ tự thay đổi.',
    planAvailable: 'Kế hoạch đã xác nhận của bạn có {count} buổi đã lên lịch để xem lại khi sẵn sàng.',
    noPlan: 'Hoàn thành đánh giá sẵn sàng và xác nhận kế hoạch trước khi dùng hướng dẫn tập luyện.',
    priorities: {
      protein: 'Bạn vẫn còn mục tiêu chất đạm trong ngày. Nếu phù hợp với sở thích và kế hoạch của bạn, hãy cân nhắc món có chất đạm và ghi lại khẩu phần thực tế.',
      fiber: 'Bạn vẫn còn mục tiêu chất xơ trong ngày. Khi phù hợp với bạn, hãy cân nhắc cách ăn có rau, đậu, trái cây hoặc ngũ cốc nguyên hạt.',
      sodium: 'Tổng natri đã xác nhận đã chạm mục tiêu trong ngày. Trong phần còn lại của ngày, hãy so sánh nước sốt, nước dùng, gia vị và nhãn thực phẩm đóng gói trước khi quyết định món phù hợp.',
      healthFocus: 'Giữ các mối quan tâm sức khỏe đã chọn trong đầu khi xem lại bữa ăn và chỉ số. Luôn dùng mục tiêu hoặc hạn chế do chuyên gia đặt ra khi có.',
      balanced: 'Chưa có so sánh mục tiêu nào cần chú ý. Hãy tiếp tục ghi bữa ăn, chỉ số và buổi tập đã xác nhận để dữ liệu riêng tư của bạn luôn hữu ích.',
    },
  },
  reminders: {
    title: 'Nhắc việc riêng tư',
    description: 'Lịch nhắc chỉ nằm trong chương trình nghị sự riêng tư của bạn. Thông báo trên màn hình khóa trong tương lai chỉ dùng nội dung trung tính.',
    kind: 'Loại nhắc việc',
    time: 'Thời gian (Asia/Bangkok)',
    days: 'Lặp lại vào',
    save: 'Lưu nhắc việc',
    saving: 'Đang lưu nhắc việc…',
    noReminders: 'Chưa có nhắc việc nào.',
    next: 'Lần tiếp theo',
    meal: 'Nhắc ghi bữa ăn',
    workout: 'Tập luyện',
    measurement: 'Đo chỉ số',
    weeklyReview: 'Đánh giá hằng tuần',
    pause: 'Tạm dừng',
    resume: 'Tiếp tục',
    update: 'Cập nhật nhắc việc',
    snoozeHour: 'Hoãn 1 giờ',
    quietHours: 'Giờ yên lặng',
    quietStart: 'Bắt đầu',
    quietEnd: 'Kết thúc',
    delete: 'Xóa',
    paused: 'Đã tạm dừng',
    deleteConfirm: 'Xóa vĩnh viễn nhắc việc này? Không thể hoàn tác.',
  },
  settings: {
    eyebrow: 'Cài đặt',
    title: 'Mục tiêu cá nhân',
    description:
      'Dùng các mục tiêu do bạn tự đặt. Mục tiêu do bác sĩ chỉ định luôn được ưu tiên.',
    calories: 'Năng lượng',
    protein: 'Chất đạm',
    fiber: 'Chất xơ',
    sodium: 'Natri',
    saveTargets: 'Lưu mục tiêu cá nhân',
    healthFocuses: 'Mối quan tâm sức khỏe',
    healthFocusDescription: 'Tùy chọn theo dõi, không phải chẩn đoán.',
    saveHealthFocuses: 'Lưu mối quan tâm sức khỏe',
    dataPrivacy: 'Quyền riêng tư và dữ liệu',
    exportData: 'Xuất dữ liệu của tôi',
    exportDescription: 'Tải các dữ liệu bữa ăn, chỉ số và tập luyện đã xác nhận theo khoảng thời gian dưới dạng CSV riêng tư. Không tạo liên kết chia sẻ.',
    exportStart: 'Ngày bắt đầu',
    exportEnd: 'Ngày kết thúc',
    exportCsv: 'Tải CSV',
    exportPdf: 'Tải báo cáo PDF',
    exportFullArchive: 'Tải toàn bộ kho lưu trữ',
    exportFullArchiveDescription: 'Tải toàn bộ dữ liệu riêng tư có cấu trúc và các tệp tải lên riêng tư hiện có trong tệp JSON có phiên bản. Hãy giữ kho lưu trữ này an toàn vì có thể chứa thông tin sức khỏe nhạy cảm.',
    deleteData: 'Xóa dữ liệu của tôi',
    deleteDataDescription: 'Xóa vĩnh viễn mọi bữa ăn, chỉ số, buổi tập, nhắc việc, hồ sơ, dữ liệu trích xuất và ảnh đã tải lên riêng tư. Không thể hoàn tác.',
    deleteDataPrompt: 'Nhập DELETE MY DATA để bật xóa vĩnh viễn',
    deletingData: 'Đang xóa dữ liệu riêng tư…',
    deleteDataError: 'Không thể xóa vĩnh viễn dữ liệu riêng tư của bạn.',
    targetsDescription:
      'Các mục tiêu này chỉ dùng cho bảng Hôm nay; chúng không phải lời khuyên y tế.',
    targetSuffix: 'mục tiêu',
    bloodPressure: 'Huyết áp',
    bloodPressureDescription: 'Ưu tiên các kiểm tra liên quan đến natri.',
    cholesterol: 'Cholesterol',
    cholesterolDescription: 'Ưu tiên các kiểm tra theo xu hướng chất xơ.',
    bloodGlucose: 'Đường huyết',
    bloodGlucoseDescription:
      'Được lưu ngay; các quy tắc an toàn về tập luyện và carbohydrate sẽ có sau.',
    uricAcid: 'Axit uric / gout',
    uricAcidDescription:
      'Được lưu ngay; các quy tắc về nguy cơ purin sẽ có sau.',
    addFocus: 'Thêm',
    removeFocus: 'Bỏ',
    focusSuffix: 'mối quan tâm sức khỏe',
    sensitiveDataNotice:
      'Chưa nhập thông tin thuốc, triệu chứng hoặc ghi chú của bác sĩ tại đây. Các dữ liệu này cần luồng hồ sơ sức khỏe mã hóa sắp tới.',
  },
  onboarding: {
    eyebrow: 'Thiết lập hồ sơ',
    title: 'Lập kế hoạch theo cuộc sống thực của bạn',
    description:
      'Lưu những gì hữu ích cho việc lên kế hoạch bữa ăn và tập tại nhà. Bạn có thể lưu một phần rồi quay lại sau.',
    complete: 'Đã hoàn tất thông tin cơ bản để lập kế hoạch',
    inProgress: 'Đang thiết lập thông tin cơ bản',
    goal: 'Mục tiêu chính',
    height: 'Chiều cao (cm)',
    weight: 'Cân nặng hiện tại (kg)',
    age: 'Tuổi',
    sex: 'Giới tính dùng cho tính toán chuyển hóa',
    activity: 'Mức độ hoạt động thường ngày',
    training: 'Kinh nghiệm tập luyện',
    sleep: 'Số giờ ngủ thường ngày',
    days: 'Ngày có thể tập',
    equipment: 'Thiết bị hiện có',
    environments: 'Môi trường tập luyện',
    restrictions: 'Hạn chế tập luyện do bác sĩ chỉ định',
    preferences: 'Ưu tiên ăn uống',
    allergies: 'Dị ứng thực phẩm',
    contexts: 'Nội dung theo dõi sức khỏe',
    injuries: 'Vấn đề vận động hiện tại',
    symptoms: 'Triệu chứng hiện tại khi tập',
    preferenceOmnivore: 'Ăn đa dạng', preferenceVegetarian: 'Ăn chay', preferenceVegan: 'Thuần chay', preferencePescatarian: 'Ăn cá', preferenceHalal: 'Halal', preferenceLowSodium: 'Ít natri', preferenceLowPurine: 'Ít purin',
    allergyMilk: 'Sữa', allergyEgg: 'Trứng', allergyFish: 'Cá', allergyShellfish: 'Hải sản có vỏ', allergyPeanut: 'Đậu phộng', allergyTreeNut: 'Các loại hạt cây', allergySoy: 'Đậu nành', allergyWheat: 'Lúa mì', allergySesame: 'Mè',
    contextBloodPressure: 'Huyết áp', contextCholesterol: 'Cholesterol', contextBloodGlucose: 'Đường huyết', contextUricAcid: 'Axit uric',
    injuryBack: 'Đau lưng', injuryJoint: 'Đau khớp', injuryBalance: 'Lo ngại thăng bằng',
    symptomNone: 'Không có triệu chứng', symptomChest: 'Khó chịu ở ngực', symptomDizziness: 'Chóng mặt', symptomBreath: 'Khó thở',
    save: 'Lưu thiết lập hồ sơ',
    goalWeightLoss: 'Giảm cân',
    goalMaintain: 'Duy trì cân nặng',
    goalMuscleGain: 'Tăng cơ',
    goalFitness: 'Thể lực',
    goalHealthTracking: 'Theo dõi sức khỏe',
    sexFemale: 'Nữ', sexMale: 'Nam', sexNotSpecified: 'Không muốn nêu',
    activitySedentary: 'Ít vận động', activityLight: 'Hoạt động nhẹ', activityModerate: 'Hoạt động vừa', activityActive: 'Hoạt động nhiều', activityVeryActive: 'Hoạt động rất nhiều',
    trainingNew: 'Mới bắt đầu tập', trainingBeginner: 'Cơ bản', trainingRegular: 'Tập thường xuyên',
    dayMon: 'T2', dayTue: 'T3', dayWed: 'T4', dayThu: 'T5', dayFri: 'T6', daySat: 'T7', daySun: 'CN',
    equipmentBodyweight: 'Trọng lượng cơ thể', equipmentChair: 'Ghế', equipmentMat: 'Thảm tập', equipmentBicycle: 'Xe đạp', equipmentTreadmill: 'Máy chạy mini', equipmentBand: 'Dây kháng lực', equipmentDumbbells: 'Tạ tay', equipmentGym: 'Phòng gym',
    environmentHome: 'Tại nhà', environmentOutdoors: 'Ngoài trời', environmentGym: 'Phòng gym',
    restrictionIntensity: 'Tránh cường độ cao', restrictionResistance: 'Tránh tập kháng lực', restrictionImpact: 'Tránh bài tập va chạm', restrictionGlucose: 'Theo dõi đường huyết',
  },
  sensitiveNotes: {
    eyebrow: 'Ghi chú sức khỏe được mã hóa',
    title: 'Ghi chú riêng tư cho kế hoạch của bạn',
    description: 'Các ghi chú này được mã hóa trước khi lưu. Chúng không xuất hiện trong lời nhắc và không dùng để chẩn đoán hoặc thay đổi thuốc.',
    medication: 'Ghi chú về thuốc hoặc an toàn khi tập',
    clinician: 'Hướng dẫn của bác sĩ',
    symptoms: 'Ghi chú bổ sung về triệu chứng',
    save: 'Lưu ghi chú đã mã hóa',
    unavailable: 'Ghi chú sức khỏe được mã hóa chưa khả dụng cho đến khi khóa mã hóa phía máy chủ được cấu hình.',
  },
  feedback: {
    targetsSaveError: 'Không thể lưu mục tiêu của bạn.',
    targetsReplayed: 'Thay đổi mục tiêu trước đó của bạn đã được lưu.',
    targetsSaved: 'Đã lưu mục tiêu cá nhân. Mục tiêu do bác sĩ chỉ định vẫn được ưu tiên khi có.',
    focusesSaveError: 'Không thể lưu các mối quan tâm sức khỏe của bạn.',
    focusesReplayed: 'Thay đổi mối quan tâm sức khỏe trước đó của bạn đã được lưu.',
    focusesSaved: 'Đã lưu các mối quan tâm sức khỏe. Những lần xem lại bữa ăn sau sẽ ưu tiên các kiểm tra đã chọn.',
    onboardingSaveError: 'Không thể lưu thiết lập hồ sơ của bạn.',
    onboardingReplayed: 'Thiết lập hồ sơ trước đó của bạn đã được lưu.',
    onboardingComplete: 'Đã lưu thiết lập hồ sơ. Hãy xem lại mức sẵn sàng tập luyện trước khi bắt đầu kế hoạch.',
    onboardingSaved: 'Đã lưu thiết lập hồ sơ. Bạn có thể hoàn thành các thông tin cơ bản còn lại bất cứ lúc nào.',
    notesSaveError: 'Không thể lưu ghi chú sức khỏe được mã hóa.',
    notesSaved: 'Đã lưu ghi chú sức khỏe được mã hóa vào hồ sơ riêng tư của bạn.',
    reportStoreError: 'Không thể lưu riêng tư báo cáo này.',
    reportExtractError: 'Không thể trích xuất báo cáo này.',
    measurementBloodPressureError: 'Hãy nhập cả hai giá trị huyết áp dương.',
    measurementCustomLabError: 'Hãy nhập tên xét nghiệm và đơn vị của nó.',
    measurementValueError: 'Hãy nhập giá trị đo dương.',
    measurementSaveError: 'Không thể lưu chỉ số này.',
    measurementReplayed: 'Chỉ số trước đó của bạn đã được ghi nhận.',
    measurementSaved: 'Chỉ số đã xác nhận được lưu vào lịch sử riêng tư của bạn.',
    measurementDeleteImageError: 'Không thể xóa ảnh nguồn này.',
    readinessSaveError: 'Không thể lưu mức sẵn sàng tập luyện.',
    readinessCleared: 'Đã xác nhận sẵn sàng tập luyện. Kế hoạch có thể được xem xét sau khi bạn chọn thiết bị và lịch tập.',
    readinessPaused: 'Tạm dừng tạo kế hoạch tập luyện cho đến khi bạn trao đổi vấn đề an toàn đã báo cáo với chuyên gia phù hợp.',
    planPreviewError: 'Không thể tạo bản xem trước kế hoạch tập.',
    planConfirmError: 'Không thể xác nhận kế hoạch tập này.',
    planReplayed: 'Xác nhận kế hoạch tập luyện trước đó của bạn đã được ghi nhận.',
    planConfirmed: 'Đã xác nhận kế hoạch tập luyện. Hãy giữ cường độ nhẹ và dừng lại nếu có triệu chứng đáng lo ngại.',
    checkinError: 'Không thể hoàn tất đánh giá hồi phục.',
    workoutLogValidation: 'Hãy nhập thời lượng, cường độ, mức yêu thích và đường huyết tùy chọn hợp lệ.',
    workoutLogSaveError: 'Không thể lưu nhật ký tập này.',
    workoutLogReview: 'Đã lưu nhật ký tập luyện. Không tăng tiến kế hoạch; hãy trao đổi về cơn đau hoặc triệu chứng đã báo cáo với chuyên gia phù hợp.',
    workoutLogSaved: 'Buổi tập đã hoàn thành được lưu vào lịch sử riêng tư của bạn.',
    mealReviewError: 'Không thể chuẩn bị bản xem lại.',
    mealReviewIncomplete: 'Bản xem lại bữa ăn chưa đầy đủ. Hãy thử lại.',
    mealSaveError: 'Không thể lưu bữa ăn này.',
    mealReplayed: 'Lần lưu trước của bạn đã được ghi nhận.',
    mealSaved: 'Đã lưu bữa ăn. Tổng hôm nay hiện dựa trên mục bạn đã xác nhận.',
    savedFoodSaveError: 'Không thể lưu món ăn cá nhân này.',
    savedFoodReplayed: 'Món ăn cá nhân của bạn đã được lưu.',
    recipeSaved: 'Đã lưu công thức vào thư viện thực phẩm riêng tư của bạn.',
    foodSaved: 'Đã lưu món ăn vào thư viện thực phẩm riêng tư của bạn.',
    savedFoodDeleted: 'Đã xóa món ăn đã lưu khỏi thư viện riêng tư.',
    savedFoodDeleteError: 'Không thể xóa món ăn đã lưu này.',
    personalFoodReview: 'Đang dùng món ăn bạn đã xác nhận trước đó. Hãy xem lại trước khi lưu bữa ăn này.',
    photoStoreError: 'Không thể lưu riêng tư ảnh này.',
    photoDeleteError: 'Không thể xóa tệp tải lên riêng tư. Hãy thử lại.',
    photoExtractError: 'Không thể trích xuất ảnh này.',
    reminderDaysRequired: 'Hãy chọn ít nhất một ngày.',
    reminderSaveError: 'Không thể lưu nhắc việc này.',
    loadMealsError: 'Không thể tải các bữa ăn hôm nay.',
    reminderUpdateError: 'Không thể cập nhật nhắc việc này.',
    reminderSaved: 'Đã lưu nhắc việc vào lịch riêng tư của bạn.',
    reminderDeleted: 'Đã xóa nhắc việc.',
    reminderPaused: 'Đã tạm dừng nhắc việc.',
    reminderResumed: 'Đã tiếp tục nhắc việc.',
    reminderSnoozed: 'Đã hoãn nhắc việc.',
    reminderRescheduled: 'Đã đổi lịch nhắc việc.',
    reportImageDeleted: 'Đã xóa ảnh báo cáo riêng tư. Chỉ số đã xác nhận vẫn được giữ lại.',
    accountDeleteError: 'Không thể xóa vĩnh viễn dữ liệu riêng tư của bạn.',
    accountDeleted: 'Dữ liệu Nourishwell riêng tư của bạn đã được xóa vĩnh viễn.',
    localeSaveError: 'Không thể lưu lựa chọn ngôn ngữ của bạn.',
    dashboardOffline: 'Bạn đang ngoại tuyến. Thông tin đã tải vẫn hiển thị, nhưng không thể thay đổi hồ sơ sức khỏe cho đến khi kết nối lại.',
    dashboardPermissionDenied: 'Không thể mở hồ sơ riêng tư của bạn. Hãy đăng nhập lại rồi thử lại.',
    dashboardRetry: 'Tải lại hồ sơ riêng tư',
    exportDateRange: 'Hãy chọn khoảng ngày hợp lệ.',
    exportCreateError: 'Không thể tạo tệp xuất này.',
  },
  safety: {
    notMedicalAdvice:
      'Thông tin này hỗ trợ sức khỏe tổng quát, không phải lời khuyên y tế.',
    reviewBeforeSaving:
      'Hãy kiểm tra các giá trị, khẩu phần giả định và nguồn trước khi lưu.',
    noAutomaticSaving: 'Không có gì được tự động lưu.',
    seekUrgentCare:
      'Hãy tìm hỗ trợ y tế khẩn cấp khi có triệu chứng nặng hoặc tình trạng cấp cứu.',
    stopTraining:
      'Dừng vận động nếu đau ngực, khó thở nhiều, ngất, chóng mặt đột ngột hoặc có triệu chứng mới đáng lo.',
    clinicianPriority:
      'Hãy làm theo hướng dẫn của bác sĩ. Mục tiêu và hạn chế do bác sĩ chỉ định luôn được ưu tiên.',
    noDiagnosis:
      'Các lựa chọn theo dõi và nhận xét về bữa ăn không phải chẩn đoán hay khuyến nghị điều trị.',
    sensitiveData:
      'Không nhập chi tiết thuốc, triệu chứng hoặc ghi chú của bác sĩ cho đến khi có hồ sơ sức khỏe được mã hóa.',
  },
};

export const copy: Record<Locale, ProductCopy> = {
  en: englishCopy,
  vi: vietnameseCopy,
};

export function isLocale(value: string | null | undefined): value is Locale {
  return (
    value !== undefined &&
    value !== null &&
    supportedLocales.includes(value as Locale)
  );
}

export function getCopy(locale: Locale | null | undefined): ProductCopy {
  return copy[locale && isLocale(locale) ? locale : 'en'];
}
