export const WORKOUT_PRESCRIPTION_POLICY = {
  version: 'conservative-prescription-policy-1',
  reviewStatus: 'unreviewed',
  reviewedVersion: null,
  reviewedAt: null,
  reviewReference: null,
  maximumSessionsPerWeek: 3,
  byTrainingHistory: {
    new_to_exercise: {
      sessionMinutes: 20,
      targetRpe: 3,
      warmupMinutes: 3,
      cooldownMinutes: 3,
      strength: { allocatedMinutes: 12, sets: 2, reps: 8, restSeconds: 60 },
      aerobicMinutes: 12,
      mobilityMinutes: 10,
    },
    beginner: {
      sessionMinutes: 25,
      targetRpe: 4,
      warmupMinutes: 3,
      cooldownMinutes: 3,
      strength: { allocatedMinutes: 15, sets: 2, reps: 10, restSeconds: 60 },
      aerobicMinutes: 16,
      mobilityMinutes: 12,
    },
    regular: {
      sessionMinutes: 30,
      targetRpe: 5,
      warmupMinutes: 4,
      cooldownMinutes: 4,
      strength: { allocatedMinutes: 18, sets: 3, reps: 8, restSeconds: 75 },
      aerobicMinutes: 20,
      mobilityMinutes: 15,
    },
  },
  modifiedMaximumRpe: 3,
  progressionCriteriaCopyKeys: [
    'workoutPlanner.progression.awaitScheduledCheckin',
    'workoutPlanner.progression.noPainOrSymptoms',
  ],
  purposeOrderByGoal: {
    weight_loss: ['aerobic', 'strength', 'mobility'],
    maintain_weight: ['strength', 'aerobic', 'mobility'],
    muscle_gain: ['strength', 'strength', 'mobility'],
    fitness: ['aerobic', 'strength', 'mobility'],
    health_tracking: ['mobility', 'aerobic', 'strength'],
  },
} as const;
